-- 中台商机信息表结构
CREATE TABLE `business_info` (
  `business_number` varchar(20) NOT NULL DEFAULT '' COMMENT '商机编号',
  `customer_id` bigint(20) NOT NULL COMMENT '客户ID',
  `customer_name` varchar(45) NOT NULL DEFAULT '' COMMENT '客户名称',
  `owner_user_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '归属人Id',
  `owner_user_name` varchar(25) NOT NULL DEFAULT '' COMMENT '归属人姓名',
  `owner_province` varchar(45) DEFAULT NULL COMMENT '所属省区code',
  `owner_city` varchar(45) DEFAULT NULL COMMENT '所属城市编码',
  `business_attribute` tinyint(4) DEFAULT '1' COMMENT '商机属性 1：日配客户 2：福利客户 3：大宗贸易 4：M端 5：BBC 6：内购',
  `sign_type_code` tinyint(4) DEFAULT NULL COMMENT '审批流类型 1:新客 2：商机',
  `his_payment_terms` int(11) DEFAULT NULL COMMENT '历史采购平均结算账期',
  `agr_cus_thi_category_code` varchar(11) DEFAULT NULL COMMENT '履约服务客户三级客户分类编码',
  `agr_cus_sec_category_code` varchar(11) DEFAULT NULL COMMENT '履约服务客户二级客户分类编码',
  `agr_cus_fir_category_code` varchar(11) DEFAULT NULL COMMENT '履约服务客户一级客户分类编码',
  `agreement_cus_name` varchar(100) DEFAULT NULL COMMENT '履约服务客户名称',
  `receipt_sign_files` json DEFAULT NULL COMMENT '签收授权附件',
  `receipt_sign_person_phone` varchar(100) DEFAULT NULL COMMENT '回单签收授权人电话',
  `receipt_sign_person` varchar(100) DEFAULT NULL COMMENT '回单签收授权人',
  `contract_sign_amount` decimal(26,2) DEFAULT NULL COMMENT '合同签约金额（万元）',
  `association_all_bid_amount` decimal(26,2) DEFAULT NULL COMMENT '汇总投标总金额（万元）',
  `association_bid_amount` decimal(26,2) DEFAULT NULL COMMENT '汇总标的金额（万元）',
  `welfare_type` tinyint(4) DEFAULT NULL COMMENT '福利类型 1福利单 2福利小店',
  `association_bid_count` int(11) DEFAULT NULL COMMENT '关联标讯数量',
  `business_source_type` tinyint(4) DEFAULT NULL COMMENT '商机来源 1投标 2非投标 3续签',
  `business_source_two_type` tinyint(4) DEFAULT NULL COMMENT '商机二级来源 1正式投标 2跟标 3未挂网 4拜访 5内邀',
  `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '是否有效 0无效 1有效',
  `temporary_status` tinyint(4) DEFAULT '0' COMMENT '是否暂存 0否 1是',
  `business_invalid_reason` tinyint(4) DEFAULT '1' COMMENT '作废原因',
  `business_surplus_valid_days` int(11) DEFAULT '9999' COMMENT '剩余有效天数',
  `approval_id` bigint(20) DEFAULT '0' COMMENT '审批ID',
  `approval_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '审批状态 0:待发起 1：审批中 2：审批完成 3：审批拒绝',
  `business_stage` tinyint(4) DEFAULT '1' COMMENT '阶段状态 1.阶段1 2.阶段2 3.阶段3 4.阶段4 5.阶段5',
  `first_category_code` varchar(11) DEFAULT '0' COMMENT '一级客户分类code',
  `second_category_code` varchar(11) DEFAULT '0' COMMENT '二级客户分类code',
  `third_category_code` varchar(11) DEFAULT '0' COMMENT '三级客户分类code',
  `customer_address_details` json DEFAULT NULL COMMENT '客户详细地址JSON',
  `customer_address_full` varchar(100) DEFAULT NULL COMMENT '客户详细地址',
  `longitude` decimal(9,6) DEFAULT '0.000000' COMMENT '经度',
  `latitude` decimal(9,6) DEFAULT '0.000000' COMMENT '纬度',
  `contact_person` varchar(45) DEFAULT '' COMMENT '联系人姓名',
  `contact_phone` varchar(18) DEFAULT '' COMMENT '联系电话',
  `contract_number` varchar(50) DEFAULT '' COMMENT '合同编号',
  `contract_type` tinyint(4) DEFAULT NULL COMMENT '合同类型 1临时合同 2正式合同',
  `contract_begin_date` date DEFAULT NULL COMMENT '合同起始日期',
  `contract_end_date` date DEFAULT NULL COMMENT '合同终止日期',
  `last_visit_time` datetime DEFAULT NULL COMMENT '最后拜访时间',
  `estimate_contract_amount` varchar(20) DEFAULT NULL COMMENT '预估合同签约金额(万元)',
  `estimate_contract_amount_sort` decimal(26,4) DEFAULT NULL COMMENT '预估合同签约金额排序',
  `types_cooperation` varchar(5000) DEFAULT NULL COMMENT '合作品类',
  `contract_cycle_int` int(11) DEFAULT NULL COMMENT '新合同周期 0小于1个月',
  `expect_sign_time` varchar(20) DEFAULT '' COMMENT '预计签约时间',
  `expect_sign_time_sort` datetime DEFAULT NULL COMMENT '预计签约时间',
  `estimate_once_amount` varchar(20) DEFAULT NULL COMMENT '预估一次性配送金额',
  `estimate_month_amount` varchar(20) DEFAULT NULL COMMENT '预估月度配送金额',
  `meals_person_count` int(9) DEFAULT NULL COMMENT '企业人数',
  `meals_avg_amount` varchar(20) DEFAULT NULL COMMENT '人均预算',
  `company_code` varchar(45) DEFAULT '' COMMENT '公司编号',
  `payment_terms` varchar(6) DEFAULT '' COMMENT '帐期编号',
  `expect_recovery_time` varchar(20) DEFAULT '' COMMENT '预计回收时间',
  `certificate_photos` json DEFAULT NULL COMMENT '企业证照资料',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(45) NOT NULL DEFAULT 'sys' COMMENT '创建人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` varchar(45) NOT NULL DEFAULT 'sys' COMMENT '更新人',
  `contract_must` tinyint(4) DEFAULT '1' COMMENT '是否需签订合同 0否 1是',
  `channel_code` varchar(2) DEFAULT NULL COMMENT '作废--渠道编号-1.大客户 2.商超(对内) 3.商超(对外) 4.大宗 5.供应链(食百) 6.供应链(食百) 7.企业购 8.其他',
  `bid_photos` json DEFAULT NULL COMMENT '作废--招标文件',
  `attach_files` json DEFAULT NULL COMMENT '作废--附件列表',
  `customer_site_photos` json DEFAULT NULL COMMENT '作废--企业经营现场拍照',
  `legal_person_photos` json DEFAULT NULL COMMENT '作废--个人证明资料（法定代表人或实际控制人）',
  `cooperation_intention_photos` json DEFAULT NULL COMMENT '作废--客户确定合作意向截图',
  `abutment_system_status` tinyint(4) DEFAULT '1' COMMENT '作废--是否对接系统',
  `bbc_pay_type` tinyint(4) DEFAULT '1' COMMENT '作废--支付类型 1餐卡/积分 2微信支付 3其他',
  `purchase_type_supply` varchar(50) DEFAULT '' COMMENT '作废--采购类型补充',
  `purchase_type` varchar(300) DEFAULT '' COMMENT '作废--采购类型json 1套餐 2自由购 3扶贫 4其他',
  `purchase_cycle_type_supply` int(11) DEFAULT '0' COMMENT '作废--周期时间补充',
  `purchase_cycle_type` tinyint(4) DEFAULT '1' COMMENT '作废--周期时间 1：6个月 2：3个月 3：1个月 4：其他',
  `purchase_cycle` tinyint(4) DEFAULT '1' COMMENT '作废--采购周期 1全年采购 2周期采购（客户下单随时发货）',
  `bbc_attribute` tinyint(4) DEFAULT '1' COMMENT '作废--BBC业务类型 1企业购商城（BBC）2福利一次性采购（下单一次性配送）',
  `back_order_type` tinyint(4) DEFAULT '1' COMMENT '作废--回单类型 0不回单 1日回单 >1周期回单',
  `busi_win_bid_supplier_count` int(9) DEFAULT NULL COMMENT '作废--中标供应商数量',
  `busi_bid_amount` varchar(20) DEFAULT NULL COMMENT '作废--标的金额',
  `expect_bid_win_share` varchar(10) DEFAULT '' COMMENT '作废--预计可履约中标份额 100.00',
  `only_supplier_status` tinyint(4) DEFAULT '0' COMMENT '作废--是否唯一供应商',
  `union_bid_status` tinyint(4) DEFAULT '0' COMMENT '作废--是否联合招标',
  `receive_time` varchar(20) DEFAULT '' COMMENT '作废--回款日期',
  `reconciliation_time` tinyint(4) DEFAULT '0' COMMENT '作废--对账日期 1:每月1-5日 2:每月6-15日 3:其它',
  `invoice_time` varchar(20) DEFAULT '' COMMENT '作废--开票日期',
  `expect_project_end_time` varchar(20) DEFAULT '' COMMENT '作废--预计项目结束时间',
  `expect_project_begin_time` varchar(20) DEFAULT '' COMMENT '作废--预计项目开始时间',
  `employees` int(11) DEFAULT NULL COMMENT '作废--作废-企业人数',
  `bbc_credit_type` varchar(50) DEFAULT '' COMMENT '作废--作废-授信类型',
  `site_name` varchar(50) DEFAULT '' COMMENT '作废--作废-站点名称',
  `invoice_requirement` tinyint(4) DEFAULT NULL COMMENT '作废--发票要求 1.专用 2.普通 3.皆可',
  `estimate_delivery_times` varchar(20) DEFAULT NULL COMMENT '作废--作废-预估配送次数',
  `business_introduction` varchar(500) DEFAULT NULL COMMENT '作废--业务模式介绍',
  `gross_profit_rate` varchar(11) DEFAULT NULL COMMENT '作废--预计毛利率',
  `expect_execute_time` varchar(40) DEFAULT '' COMMENT '作废--预计履约时间',
  `contract_cycle` varchar(50) DEFAULT NULL COMMENT '作废--合同周期',
  `price_set_type` varchar(20) DEFAULT '' COMMENT '作废--定价方式 编号,编号',
  `price_date` tinyint(4) DEFAULT NULL COMMENT '作废--报价日期',
  `price_period` tinyint(4) DEFAULT NULL COMMENT '作废--报价周期 1:每天 2:每周 3:每半月4：每月',
  `price_type` tinyint(4) DEFAULT NULL COMMENT '作废--报价类型 1:下单前报价  2:发货前报价  3:发货后报价',
  `other_needs` varchar(45) DEFAULT NULL COMMENT '作废--其他需求 1:餐卡、2:福利、3:商城对接、4:微信支付、5:无',
  `guide_user_name` varchar(25) DEFAULT NULL COMMENT '作废--指导人名称',
  `guide_user_id` bigint(20) DEFAULT NULL COMMENT '作废--指导人Id',
  `shipper_name` varchar(30) NOT NULL DEFAULT '永辉彩食鲜' COMMENT '租户简称',
  `shipper_code` varchar(20) NOT NULL DEFAULT 'YHCSX' COMMENT '租户编码',
  PRIMARY KEY (`business_number`) USING BTREE,
  KEY `idx_sales_user_id_time` (`owner_user_id`,`business_number`,`customer_id`,`create_time`,`update_time`) USING BTREE,
  KEY `idx_id_attribute` (`customer_id`,`business_attribute`) USING BTREE,
  KEY `idx_contract_number` (`contract_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合作商机表';



his_payment_terms	1	#N/A	NULL	COMMENT	'历史采购平均结算账期',
agr_cus_thi_category_code	1	#N/A	NULL	COMMENT	'履约服务客户三级客户分类编码',
agr_cus_sec_category_code	1	#N/A	NULL	COMMENT	'履约服务客户二级客户分类编码',
agr_cus_fir_category_code	1	#N/A	NULL	COMMENT	'履约服务客户一级客户分类编码',
agreement_cus_name	1	#N/A	NULL	COMMENT	'履约服务客户名称',
receipt_sign_files	1	#N/A	NULL	COMMENT	'签收授权附件',
receipt_sign_person_phone	1	#N/A	NULL	COMMENT	'回单签收授权人电话',
receipt_sign_person	1	#N/A	NULL	COMMENT	'回单签收授权人',
contract_sign_amount	1	#N/A	NULL	COMMENT	'合同签约金额（万元）',
association_all_bid_amount	1	#N/A	NULL	COMMENT	'汇总投标总金额（万元）',
association_bid_amount	1	#N/A	NULL	COMMENT	'汇总标的金额（万元）',
association_bid_count	1	#N/A	NULL	COMMENT	'关联标讯数量',
business_source_type	1	#N/A	NULL	COMMENT	'商机来源
business_source_two_type	1	#N/A	NULL	COMMENT	'商机二级来源
