-- 财务管报导入相关表结构
-- 财务管报_调整单导入_人员调整
CREATE TABLE `source_fis_r_m_adjustment_staff_import` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `this_subject_code` varchar(64) NOT NULL COMMENT '本方主体编码',
  `this_subject_name` varchar(64) NOT NULL COMMENT '本方主体名称',
  `accounting_period` varchar(64) NOT NULL COMMENT '会计期间',
  `own_report` varchar(64) NOT NULL COMMENT '所属报表',
  `order_code` varchar(64) NOT NULL COMMENT '单据编号',
  `adjustment_type` varchar(64) NOT NULL COMMENT '调整类型',
  `company_code` varchar(64) NOT NULL COMMENT '公司编码',
  `company_name` varchar(64) NOT NULL COMMENT '公司名称',
  `SAP_account_code` varchar(64) DEFAULT NULL COMMENT 'SAP科目编码',
  `SAP_account_name` varchar(64) DEFAULT NULL COMMENT 'SAP科目名称',
  `cost_center_code` varchar(64) DEFAULT NULL COMMENT '成本中心编码',
  `cost_center_name` varchar(64) DEFAULT NULL COMMENT '成本中心名称',
  `first_category_code` varchar(64) DEFAULT NULL COMMENT '一级部门编码',
  `first_category_name` varchar(64) DEFAULT NULL COMMENT '一级部门名称',
  `second_category_code` varchar(64) DEFAULT NULL COMMENT '二级部门编码',
  `second_category_name` varchar(64) DEFAULT NULL COMMENT '二级部门名称',
  `other_period` varchar(64) DEFAULT NULL COMMENT '对方期间',
  `other_company_code` varchar(64) DEFAULT NULL COMMENT '对方公司编码',
  `other_company_name` varchar(64) DEFAULT NULL COMMENT '对方公司名称',
  `other_subject_code` varchar(64) DEFAULT NULL COMMENT '对方主体编码',
  `other_subject_name` varchar(64) DEFAULT NULL COMMENT '对方主体名称',
   staff_type_code    varchar(64) DEFAULT NULL COMMENT '员工属性',
   staff_type_name    varchar(64) DEFAULT NULL COMMENT '员工名称',
  `adjustment_number` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '调整人数',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注',
  `update_by` varchar(64) NOT NULL DEFAULT 'sys' COMMENT '更新人',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` varchar(64) NOT NULL DEFAULT 'sys' COMMENT '创建人',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `months` varchar(64) NOT NULL COMMENT '交割月份',
  PRIMARY KEY (`id`),
  KEY `source_fis_r_m_adjustment_import_this_subject_code_IDX` (`this_subject_code`,`this_subject_name`,`months`,`own_report`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='财务管报_调整单导入_人员调整';


-- 财务管报_调整单导入_后台收支费用
CREATE TABLE `source_fis_r_m_adjustment_back_expense_import` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `this_subject_code` varchar(64) NOT NULL COMMENT '本方主体编码',
  `this_subject_name` varchar(64) NOT NULL COMMENT '本方主体名称',
  `accounting_period` varchar(64) NOT NULL COMMENT '会计期间',
  `own_report` varchar(64) NOT NULL COMMENT '所属报表',
  `order_code` varchar(64) NOT NULL COMMENT '单据编号',
  `adjustment_type` varchar(64) NOT NULL COMMENT '调整类型',
  `company_code` varchar(64) NOT NULL COMMENT '公司编码',
  `company_name` varchar(64) NOT NULL COMMENT '公司名称',
  `cost_center_code` varchar(64) DEFAULT NULL COMMENT '成本中心编码',
  `cost_center_name` varchar(64) DEFAULT NULL COMMENT '成本中心名称',
  `back_income_expense_business_type` varchar(64) DEFAULT NULL COMMENT '后台收支业务类型',
  `category_name` varchar(64) DEFAULT NULL COMMENT '品类',
  `back_income_expense_type` varchar(64) DEFAULT NULL COMMENT '后台收支类型',
  `other_period` varchar(64) DEFAULT NULL COMMENT '对方期间',
  `other_company_code` varchar(64) DEFAULT NULL COMMENT '对方公司编码',
  `other_company_name` varchar(64) DEFAULT NULL COMMENT '对方公司名称',
  `other_subject_code` varchar(64) DEFAULT NULL COMMENT '对方主体编码',
  `other_subject_name` varchar(64) DEFAULT NULL COMMENT '对方主体名称',
  `adjustment_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '调整金额',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注',
  `update_by` varchar(64) NOT NULL DEFAULT 'sys' COMMENT '更新人',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` varchar(64) NOT NULL DEFAULT 'sys' COMMENT '创建人',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `months` varchar(64) NOT NULL COMMENT '交割月份',
  PRIMARY KEY (`id`),
  KEY `source_fis_r_m_adjustment_import_this_subject_code_IDX` (`this_subject_code`,`this_subject_name`,`months`,`own_report`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='财务管报_调整单导入_后台费用';



-- 财务管报_调整单导入_销售明细 test_csx_data_market.source_fis_r_m_adjustment_sale_import definition

CREATE TABLE `source_fis_r_m_adjustment_sale_import` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `this_subject_code` varchar(64) NOT NULL COMMENT '本方主体编码',
  `this_subject_name` varchar(64) NOT NULL COMMENT '本方主体名称',
  `accounting_period` varchar(64) NOT NULL COMMENT '会计期间',
  `own_report` varchar(64) NOT NULL COMMENT '所属报表',
  `order_code` varchar(64) NOT NULL COMMENT '单据编号',
  `adjustment_type` varchar(64) NOT NULL COMMENT '调整类型',
  `company_code` varchar(64) NOT NULL COMMENT '公司编码',
  `company_name` varchar(64) NOT NULL COMMENT '公司名称',
  `cost_center_code` varchar(64) DEFAULT NULL COMMENT '成本中心编码',
  `cost_center_name` varchar(64) DEFAULT NULL COMMENT '成本中心名称',
  `channel_name` varchar(64) DEFAULT NULL COMMENT '渠道',
  `business_type` varchar(64) DEFAULT NULL COMMENT '业务类型',
  `first_category_name` varchar(64) DEFAULT NULL COMMENT '企业一级分类',
  `category_name` varchar(64) DEFAULT NULL COMMENT '品类',
  `is_factory_goods_desc` varchar(64) DEFAULT NULL COMMENT '是加工商品',
  `is_process_goods` varchar(64) DEFAULT NULL COMMENT '是否代加工',
  `delivery_type` varchar(64) DEFAULT NULL COMMENT '配送模式',
  `run_type` varchar(64) DEFAULT NULL COMMENT '经营模式',
  `customer_name` varchar(64) DEFAULT NULL COMMENT '新老客',
  `other_period` varchar(64) DEFAULT NULL COMMENT '对方期间',
  `other_company_code` varchar(64) DEFAULT NULL COMMENT '对方公司编码',
  `other_company_name` varchar(64) DEFAULT NULL COMMENT '对方公司名称',
  `other_subject_code` varchar(64) DEFAULT NULL COMMENT '对方主体编码',
  `other_subject_name` varchar(64) DEFAULT NULL COMMENT '对方主体名称',
  `sales_value` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '含税销售额',
  `tax_free_sales_value` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '不含税销售额',
  `cost` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '含税定价成本',
  `tax_free_cost` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '不含税定价成本',
  `raw_material_cost` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '定价成本_原料',
  `package_material_cost` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '定价成本_包材',
  `subsidiary_material_cost` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '定价成本_辅材',
  `labor_cost` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '定价成本_人工',
  `machine_cost` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '定价成本_机时',
  `other_cost` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '定价成本_其他',
  `customer_num` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '客户数量',
  `adjustment_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '调整金额',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注',
  `update_by` varchar(64) NOT NULL DEFAULT 'sys' COMMENT '更新人',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` varchar(64) NOT NULL DEFAULT 'sys' COMMENT '创建人',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `months` varchar(64) NOT NULL COMMENT '交割月份',
  PRIMARY KEY (`id`),
  KEY `source_fis_r_m_adjustment_import_this_subject_code_IDX` (`this_subject_code`,`this_subject_name`,`months`,`own_report`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COMMENT='财务管报_调整单导入_销售明细';


--  财务管报利润表导入 test_csx_data_market.source_fis_r_m_profit_import definition

CREATE TABLE `source_fis_r_m_profit_import` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `belong_level` varchar(64) NOT NULL COMMENT '1、大区 2 省区、3、城市',
  `belong_city_name` varchar(64) NOT NULL COMMENT '1、大区 2 省区、3、城市',
  `project_type_name` varchar(255) NOT NULL COMMENT '项目',
  `total_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '合计金额',
  `bulk2_external_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '大宗2对外金额',
  `bulk_trade_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '大宗交易金额',
  `city_service_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '城市服务商金额',
  `daily_delivery_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '日配金额',
  `welfare_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '福利金额',
  `province_bulk_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '省区大宗金额',
  `wholesale_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '批发内购金额',
  `bbc_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT 'BBC金额',
  `supermarket_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '商超金额',
  `supermarket_machine_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '商超代加工金额',
  `bulk2_related_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '大宗2关联交易',
  `platform_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '平台金额',
  `update_by` varchar(64) NOT NULL DEFAULT 'sys' COMMENT '更新人',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` varchar(64) NOT NULL DEFAULT 'sys' COMMENT '创建人',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `months` varchar(64) NOT NULL COMMENT '交割月份',
  PRIMARY KEY (`id`),
  KEY `source_fis_r_m_profit_import_belong_level_IDX` (`belong_level`,`belong_city_name`,`months`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=487 DEFAULT CHARSET=utf8mb4 COMMENT='财务管报利润表导入';


-- 财务管报_调整单导入_费用明细 test_csx_data_market.source_fis_r_m_adjustment_expense_import definition

CREATE TABLE `source_fis_r_m_adjustment_expense_import` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `this_subject_code` varchar(64) NOT NULL COMMENT '本方主体编码',
  `this_subject_name` varchar(64) NOT NULL COMMENT '本方主体名称',
  `accounting_period` varchar(64) NOT NULL COMMENT '会计期间',
  `own_report` varchar(64) NOT NULL COMMENT '所属报表',
  `order_code` varchar(64) NOT NULL COMMENT '单据编号',
  `adjustment_type` varchar(64) NOT NULL COMMENT '调整类型',
  `company_code` varchar(64) NOT NULL COMMENT '公司编码',
  `company_name` varchar(64) NOT NULL COMMENT '公司名称',
  `SAP_account_code` varchar(64) DEFAULT NULL COMMENT 'SAP科目编码',
  `SAP_account_name` varchar(64) DEFAULT NULL COMMENT 'SAP科目名称',
  `cost_center_code` varchar(64) DEFAULT NULL COMMENT '成本中心编码',
  `cost_center_name` varchar(64) DEFAULT NULL COMMENT '成本中心名称',
  `first_category_code` varchar(64) DEFAULT NULL COMMENT '一级部门编码',
  `first_category_name` varchar(64) DEFAULT NULL COMMENT '一级部门名称',
  `second_category_code` varchar(64) DEFAULT NULL COMMENT '二级部门编码',
  `second_category_name` varchar(64) DEFAULT NULL COMMENT '二级部门名称',
  `other_period` varchar(64) DEFAULT NULL COMMENT '对方期间',
  `other_company_code` varchar(64) DEFAULT NULL COMMENT '对方公司编码',
  `other_company_name` varchar(64) DEFAULT NULL COMMENT '对方公司名称',
  `other_subject_code` varchar(64) DEFAULT NULL COMMENT '对方主体编码',
  `other_subject_name` varchar(64) DEFAULT NULL COMMENT '对方主体名称',
  `csx_account_code` varchar(64) DEFAULT NULL COMMENT '彩食鲜科目编码',
  `csx_account_name` varchar(64) DEFAULT NULL COMMENT '彩食鲜科目名称',
  `adjustment_amount` decimal(26,6) NOT NULL DEFAULT '0.000000' COMMENT '调整金额',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注',
  `update_by` varchar(64) NOT NULL DEFAULT 'sys' COMMENT '更新人',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` varchar(64) NOT NULL DEFAULT 'sys' COMMENT '创建人',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `months` varchar(64) NOT NULL COMMENT '交割月份',
  PRIMARY KEY (`id`),
  KEY `source_fis_r_m_adjustment_import_this_subject_code_IDX` (`this_subject_code`,`this_subject_name`,`months`,`own_report`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='财务管报_调整单导入_费用明细';