CREATE table csx_dw.crm_credit_rating
(
sflag string comment '客户类型',
hkont string comment '科目',
account_name string comment '科目名称',
comp_code string comment '帐龄公司代码',
comp_name string comment '帐龄公司代码名称',
company_code string comment 'CRM公司代码',
sale_company_code string comment '销售公司代码',
sales_province_code string comment '省区编码',
sales_province string comment '省区名称',
sales_city_code string comment '城市编码',
sales_city string comment '城市名称',
province_code string comment '客户归属省区',
province_name string comment '客户归属省区名称',
city_code string comment '客户归属城市',
city_name string comment '客户归属城市名称',
sales_name string comment '销售员',
work_no string comment '工号',
customer_no string comment '客户编码',
customer_name string comment '客户名称',
attribute string comment '客户属性',
credit_limit string comment '固定额度',
temp_credit_limit string comment '临时额度',
channel string comment '分销渠道',
first_category string comment '一级性质',
second_category string comment '二级性质',
third_category string comment '三级性质',
sign_date string comment '签约日期',
zterm string comment '账期类型',
diff string comment '帐期时长',
ac_wdq decimal(26,6) comment '未到期账款',
ac_15d decimal(26,6) comment '逾期1-15天',
ac_30d decimal(26,6) comment '逾期16-30天',
ac_60d decimal(26,6) comment '逾期31-60天',
ac_90d decimal(26,6) comment '逾期61-90天',
ac_120d decimal(26,6) comment '逾期91-120天',
ac_180d DECIMAL(26,6) comment '逾期121-180天',
ac_365d DECIMAL(26,6) comment '逾期181-365天',
ac_2y DECIMAL(26,6) comment '逾期1-2年',
ac_3y DECIMAL(26,6) comment '逾期2-3年',
ac_over3y decimal(26,6) comment '逾期3年以上',
ac_all DECIMAL(26,6) comment '应收账款统计',
overdue_account DECIMAL(26,6) comment '逾期账款统计',
use_ac_all DECIMAL(26,6) comment '已使用额度',
avg_sale DECIMAL(26,6) comment '过去30个自然日日均销售',
diff_01 string comment '账期',
index_data string comment '转换',
unuse_ac DECIMAL(26,6) comment '未使用额度',
new_credit_limit DECIMAL(26,6) comment '重新计算的信控固定额度',
future_amount DECIMAL(26,6) comment '未来信控额度',
surplus_credit DECIMAL(26,6) comment '剩余信控',
credit_limit1 DECIMAL(26,6) comment '新调整信控额度',
min_sdt string comment '首单日期',
change_type     string comment '是否调整'
)comment 'CRM信控预测'
PARTITIONED BY (sdt STRING COMMENT'日期分区')
STORED AS PARQUET
LOCATION 
 'hdfs://nameservice1/user/hive/warehouse/csx_dw.db/crm_credit_rating'