set hive.map.aggr = true; --顶端聚合
set hive.groupby.skewindata=false; --数据倾斜
set hive.exec.parallel=true; --可以控制一个sql中多个可并行执行的job
--控制对于同一个sql来说同时可以运行的job的最大值,该参数默认为8
set hive.exec.parallel.thread.number=8;
set hive.exec.dynamic.partition.mode=nonstrict; --动态分区模式：strict至少要有个静态分区，nostrict不限制
set hive.exec.dynamic.partition=true; --开户动态分区
set hive.exec.max.dynamic.partitions.pernode=1000000;--每个mapper节点最多创建1000个分区
set mapreduce.job.queuename=caishixian;  --使用队列
set hive.support.quoted.identifiers=none;  -- 查出剩余所有字段

SET i_edate = '${START_DATE}';


SET s_date=regexp_replace(to_date(trunc(${hiveconf:i_edate},'YY')),'-','');

-- SELECT ${hiveconf:s_date},substr(regexp_replace(trunc(${hiveconf:i_edate},'YY'),'-',''),1,4) as sales_year,
--         substr(regexp_replace(trunc(${hiveconf:i_edate},'MM'),'-',''),1,6) as sales_months;

-- 计算月至今客户销售
-- 1.合计
-- SHOW
-- CREATE TABLE csx_dw.ads_sale_customer_division_level_sales;
INSERT overwrite table csx_dw.ads_supply_customer_division_level_sales partition(sdt,date_m)
SELECT 
    sales_year,
        sales_months,
        layer,
       business_division_code,
       business_division_name,
       purchase_group_code,
       purchase_group_name,
       customer_no,
       customer_name,
       attribute_code,
       `attribute`,
       first_category_code,
       first_category,
       second_category_code,
       second_category,
       third_category_code,
       third_category,
       sales_province_code,
       sales_province,
       is_copemate_order,
       channel,
       channel_name,
       province_code,
       province_name,
       city_code,
       city_name,
       city_group_code,
       city_group_name,
       city_real,
       cityjob,
       province_manager_id,
       province_manager_work_no,
       province_manager_name,
       sales_sku,
        sales_days,
       sales_value,
       sales_qty,
       profit,
       front_profit,
      coalesce(profit/sales_value,0) AS profit_rate,
        return_amt,
        rank()over(partition by layer,channel,province_code order by sales_value desc ) as rank_num,
        current_timestamp() as write_time,
        regexp_replace(${hiveconf:i_edate},'-','') sdt,
        'm' as date_m
FROM
  ( SELECT substr(sdt,1,4) as sales_year,
            substr(sdt,1,6) as sales_months,
            '1' AS LAYER,
           '00' AS business_division_code,
           '合计' AS business_division_name,
           '00' AS purchase_group_code,
           '小计'AS purchase_group_name,
           customer_no,
           customer_name,
           attribute_code,
           `attribute`,
           first_category_code,
           first_category,
           second_category_code,
           second_category,
           third_category_code,
           third_category,
           sales_province_code,
           sales_province,
           sales_name,
           sales_phone,
           supervisor_id,
           supervisor_work_no,
           supervisor_name,
           city_manager_id,
           city_manager_work_no,
           city_manager_name,
           item_province_manager_id,
           item_province_manager_work_no,
           item_province_manager_name,
           org_code,
           org_name,
           is_copemate_order,
           channel,
           channel_name,
           province_code,
           province_name,
           city_code,
           city_name,
           city_group_code,
           city_group_name,
           city_real,
           cityjob,
           province_manager_id,
           province_manager_work_no,
           province_manager_name,
           COUNT(DISTINCT goods_code) AS sales_sku,
           count(DISTINCT sdt) AS sales_days,
           sum(sales_value)AS sales_value,
           sum(sales_qty)AS sales_qty,
           sum(profit)AS profit,
           sum(front_profit) AS front_profit,
           sum(profit)/sum(sales_value) AS profit_rate,
           sum(CASE
                   WHEN return_flag='X' THEN sales_value
               END) AS return_amt
   FROM csx_dw.dws_sale_r_d_customer_sale
   WHERE sdt >= ${hiveconf:s_date}
   and sdt<=regexp_replace(to_date(${hiveconf:i_edate}),'-','') 
   GROUP BY customer_no,
            customer_name,
            attribute_code,
            `attribute`,
            first_category_code,
            first_category,
            second_category_code,
            second_category,
            third_category_code,
            third_category,
            sales_province_code,
            sales_province,
            sales_name,
            sales_phone,
            supervisor_id,
            supervisor_work_no,
            supervisor_name,
            city_manager_id,
            city_manager_work_no,
            city_manager_name,
            item_province_manager_id,
            item_province_manager_work_no,
            item_province_manager_name,
            org_code,
            org_name,
            is_copemate_order,
            channel,
            channel_name,
            province_code,
            province_name,
            city_code,
            city_name,
            city_group_code,
            city_group_name,
            city_real,
            cityjob,
            province_manager_id,
            province_manager_work_no,
            province_manager_name,substr(sdt,1,4) ,
            substr(sdt,1,6) 
            --采购级别
UNION ALL
SELECT substr(sdt,1,4) as sales_year,
            substr(sdt,1,6) as sales_months,
            '2' AS LAYER,
                 business_division_code,
                 business_division_name,
                 '00' AS purchase_group_code,
                 '小计'AS purchase_group_name,
                 customer_no,
                 customer_name,
                 attribute_code,
                 `attribute`,
                 first_category_code,
                 first_category,
                 second_category_code,
                 second_category,
                 third_category_code,
                 third_category,
                 sales_province_code,
                 sales_province,
                 sales_name,
                 sales_phone,
                 supervisor_id,
                 supervisor_work_no,
                 supervisor_name,
                 city_manager_id,
                 city_manager_work_no,
                 city_manager_name,
                 item_province_manager_id,
                 item_province_manager_work_no,
                 item_province_manager_name,
                 org_code,
                 org_name,
                 is_copemate_order,
                 channel,
                 channel_name,
                 province_code,
                 province_name,
                 city_code,
                 city_name,
                 city_group_code,
                 city_group_name,
                 city_real,
                 cityjob,
                 province_manager_id,
                 province_manager_work_no,
                 province_manager_name,
                 COUNT(DISTINCT goods_code) AS sales_sku,
                 count(DISTINCT sdt) AS sales_days,
                 sum(sales_value)AS sales_value,
                 sum(sales_qty)AS sales_qty,
                 sum(profit)AS profit,
                 sum(front_profit) AS front_profit,
                 sum(profit)/sum(sales_value) AS profit_rate,
                 sum(CASE
                         WHEN return_flag='X' THEN sales_value
                     END) AS return_amt
   FROM csx_dw.dws_sale_r_d_customer_sale a
   JOIN
     (SELECT business_division_code,
             business_division_name,
             category_small_code
      FROM csx_dw.dws_basic_w_a_category_m
      WHERE sdt='current') b ON a.category_small_code=b.category_small_code
   WHERE sdt >= ${hiveconf:s_date}
   and  sdt<=regexp_replace(to_date(${hiveconf:i_edate}),'-','') 
   GROUP BY customer_no,
            customer_name,
            attribute_code,
            `attribute`,
            first_category_code,
            first_category,
            second_category_code,
            second_category,
            third_category_code,
            third_category,
            sales_province_code,
            sales_province,
            sales_name,
            sales_phone,
            supervisor_id,
            supervisor_work_no,
            supervisor_name,
            city_manager_id,
            city_manager_work_no,
            city_manager_name,
            item_province_manager_id,
            item_province_manager_work_no,
            item_province_manager_name,
            org_code,
            org_name,
            is_copemate_order,
            channel,
            channel_name,
            province_code,
            province_name,
            city_code,
            city_name,
            city_group_code,
            city_group_name,
            city_real,
            cityjob,
            province_manager_id,
            province_manager_work_no,
            province_manager_name,
            business_division_code,
            business_division_name,substr(sdt,1,4),
            substr(sdt,1,6) 
-- 课组级别
UNION ALL 
SELECT 
substr(sdt,1,4) as sales_year,
            substr(sdt,1,6) as sales_months,
            '3' AS LAYER,
                 business_division_code,
                 business_division_name,
                 purchase_group_code,
                 purchase_group_name,
                 customer_no,
                 customer_name,
                 attribute_code,
                 `attribute`,
                 first_category_code,
                 first_category,
                 second_category_code,
                 second_category,
                 third_category_code,
                 third_category,
                 sales_province_code,
                 sales_province,
                 sales_name,
                 sales_phone,
                 supervisor_id,
                 supervisor_work_no,
                 supervisor_name,
                 city_manager_id,
                 city_manager_work_no,
                 city_manager_name,
                 item_province_manager_id,
                 item_province_manager_work_no,
                 item_province_manager_name,
                 org_code,
                 org_name,
                 is_copemate_order,
                 channel,
                 channel_name,
                 province_code,
                 province_name,
                 city_code,
                 city_name,
                 city_group_code,
                 city_group_name,
                 city_real,
                 cityjob,
                 province_manager_id,
                 province_manager_work_no,
                 province_manager_name,
                 COUNT(DISTINCT goods_code) AS sales_sku,
                 count(DISTINCT sdt) AS sales_days,
                 sum(sales_value)AS sales_value,
                 sum(sales_qty)AS sales_qty,
                 sum(profit)AS profit,
                 sum(front_profit) AS front_profit,
                 sum(profit)/sum(sales_value) AS profit_rate,
                 sum(CASE
                         WHEN return_flag='X' THEN sales_value
                     END) AS return_amt
   FROM csx_dw.dws_sale_r_d_customer_sale a
   JOIN
     (SELECT business_division_code,
             business_division_name,
             category_small_code,
             purchase_group_code,
             purchase_group_name
      FROM csx_dw.dws_basic_w_a_category_m
      WHERE sdt='current') b ON a.category_small_code=b.category_small_code
   WHERE sdt >= ${hiveconf:s_date} and sdt<=regexp_replace(to_date(${hiveconf:i_edate}),'-','') 
   GROUP BY customer_no,
            customer_name,
            attribute_code,
            `attribute`,
            first_category_code,
            first_category,
            second_category_code,
            second_category,
            third_category_code,
            third_category,
            sales_province_code,
            sales_province,
            sales_name,
            sales_phone,
            supervisor_id,
            supervisor_work_no,
            supervisor_name,
            city_manager_id,
            city_manager_work_no,
            city_manager_name,
            item_province_manager_id,
            item_province_manager_work_no,
            item_province_manager_name,
            org_code,
            org_name,
            is_copemate_order,
            channel,
            channel_name,
            province_code,
            province_name,
            city_code,
            city_name,
            city_group_code,
            city_group_name,
            city_real,
            cityjob,
            province_manager_id,
            province_manager_work_no,
            province_manager_name,
            business_division_code,
            business_division_name,
            purchase_group_code,
            purchase_group_name,substr(sdt,1,4),
            substr(sdt,1,6) )a
          ;
INSERT into table csx_dw.ads_supply_customer_division_level_sales partition(sdt,date_m)
SELECT  

    sales_year,
        sales_months,
        layer,
       business_division_code,
       business_division_name,
       purchase_group_code,
       purchase_group_name,
       customer_no,
       customer_name,
       attribute_code,
       `attribute`,
       first_category_code,
       first_category,
       second_category_code,
       second_category,
       third_category_code,
       third_category,
       sales_province_code,
       sales_province,
       is_copemate_order,
       channel,
       channel_name,
       province_code,
       province_name,
       city_code,
       city_name,
       city_group_code,
       city_group_name,
       city_real,
       cityjob,
       province_manager_id,
       province_manager_work_no,
       province_manager_name,
       sales_sku,
        sales_days,
       sales_value,
       sales_qty,
       profit,
       front_profit,
      coalesce(profit/sales_value,0) AS profit_rate,
        return_amt,
        rank()over(partition by layer,channel,province_code order by sales_value desc ) as rank_num,
        current_timestamp() as write_time,
        regexp_replace(${hiveconf:i_edate},'-',''),
        'y' date_m
FROM
  ( SELECT substr(sdt,1,4) as sales_year,
            '' as sales_months,
            '1' AS LAYER,
           '00' AS business_division_code,
           '合计' AS business_division_name,
           '00' AS purchase_group_code,
           '小计'AS purchase_group_name,
           customer_no,
           customer_name,
           attribute_code,
           `attribute`,
           first_category_code,
           first_category,
           second_category_code,
           second_category,
           third_category_code,
           third_category,
           sales_province_code,
           sales_province,
           sales_name,
           sales_phone,
           supervisor_id,
           supervisor_work_no,
           supervisor_name,
           city_manager_id,
           city_manager_work_no,
           city_manager_name,
           item_province_manager_id,
           item_province_manager_work_no,
           item_province_manager_name,
           org_code,
           org_name,
           is_copemate_order,
           channel,
           channel_name,
           province_code,
           province_name,
           city_code,
           city_name,
           city_group_code,
           city_group_name,
           city_real,
           cityjob,
           province_manager_id,
           province_manager_work_no,
           province_manager_name,
           COUNT(DISTINCT goods_code) AS sales_sku,
           count(DISTINCT sdt) AS sales_days,
           sum(sales_value)AS sales_value,
           sum(sales_qty)AS sales_qty,
           sum(profit)AS profit,
           sum(front_profit) AS front_profit,
           sum(profit)/sum(sales_value) AS profit_rate,
           sum(CASE
                   WHEN return_flag='X' THEN sales_value
               END) AS return_amt
   FROM csx_dw.dws_sale_r_d_customer_sale
   WHERE sdt >= ${hiveconf:s_date}
   and sdt<=regexp_replace(to_date(${hiveconf:i_edate}),'-','') 
   GROUP BY customer_no,
            customer_name,
            attribute_code,
            `attribute`,
            first_category_code,
            first_category,
            second_category_code,
            second_category,
            third_category_code,
            third_category,
            sales_province_code,
            sales_province,
            sales_name,
            sales_phone,
            supervisor_id,
            supervisor_work_no,
            supervisor_name,
            city_manager_id,
            city_manager_work_no,
            city_manager_name,
            item_province_manager_id,
            item_province_manager_work_no,
            item_province_manager_name,
            org_code,
            org_name,
            is_copemate_order,
            channel,
            channel_name,
            province_code,
            province_name,
            city_code,
            city_name,
            city_group_code,
            city_group_name,
            city_real,
            cityjob,
            province_manager_id,
            province_manager_work_no,
            province_manager_name,substr(sdt,1,4)
            --采购级别
UNION ALL
SELECT substr(sdt,1,4) as sales_year,
            '' as sales_months,
            '2' AS LAYER,
                 business_division_code,
                 business_division_name,
                 '00' AS purchase_group_code,
                 '小计'AS purchase_group_name,
                 customer_no,
                 customer_name,
                 attribute_code,
                 `attribute`,
                 first_category_code,
                 first_category,
                 second_category_code,
                 second_category,
                 third_category_code,
                 third_category,
                 sales_province_code,
                 sales_province,
                 sales_name,
                 sales_phone,
                 supervisor_id,
                 supervisor_work_no,
                 supervisor_name,
                 city_manager_id,
                 city_manager_work_no,
                 city_manager_name,
                 item_province_manager_id,
                 item_province_manager_work_no,
                 item_province_manager_name,
                 org_code,
                 org_name,
                 is_copemate_order,
                 channel,
                 channel_name,
                 province_code,
                 province_name,
                 city_code,
                 city_name,
                 city_group_code,
                 city_group_name,
                 city_real,
                 cityjob,
                 province_manager_id,
                 province_manager_work_no,
                 province_manager_name,
                 COUNT(DISTINCT goods_code) AS sales_sku,
                 count(DISTINCT sdt) AS sales_days,
                 sum(sales_value)AS sales_value,
                 sum(sales_qty)AS sales_qty,
                 sum(profit)AS profit,
                 sum(front_profit) AS front_profit,
                 sum(profit)/sum(sales_value) AS profit_rate,
                 sum(CASE
                         WHEN return_flag='X' THEN sales_value
                     END) AS return_amt
   FROM csx_dw.dws_sale_r_d_customer_sale a
   JOIN
     (SELECT business_division_code,
             business_division_name,
             category_small_code
      FROM csx_dw.dws_basic_w_a_category_m
      WHERE sdt='current') b ON a.category_small_code=b.category_small_code
   WHERE sdt >= ${hiveconf:s_date}
   and  sdt<=regexp_replace(to_date(${hiveconf:i_edate}),'-','') 
   GROUP BY customer_no,
            customer_name,
            attribute_code,
            `attribute`,
            first_category_code,
            first_category,
            second_category_code,
            second_category,
            third_category_code,
            third_category,
            sales_province_code,
            sales_province,
            sales_name,
            sales_phone,
            supervisor_id,
            supervisor_work_no,
            supervisor_name,
            city_manager_id,
            city_manager_work_no,
            city_manager_name,
            item_province_manager_id,
            item_province_manager_work_no,
            item_province_manager_name,
            org_code,
            org_name,
            is_copemate_order,
            channel,
            channel_name,
            province_code,
            province_name,
            city_code,
            city_name,
            city_group_code,
            city_group_name,
            city_real,
            cityjob,
            province_manager_id,
            province_manager_work_no,
            province_manager_name,
            business_division_code,
            business_division_name,
            substr(sdt,1,4)
-- 课组级别
UNION ALL 
SELECT 
        substr(sdt,1,4) as sales_year,
           '' as sales_months,
            '3' AS LAYER,
                 business_division_code,
                 business_division_name,
                 purchase_group_code,
                 purchase_group_name,
                 customer_no,
                 customer_name,
                 attribute_code,
                 `attribute`,
                 first_category_code,
                 first_category,
                 second_category_code,
                 second_category,
                 third_category_code,
                 third_category,
                 sales_province_code,
                 sales_province,
                 sales_name,
                 sales_phone,
                 supervisor_id,
                 supervisor_work_no,
                 supervisor_name,
                 city_manager_id,
                 city_manager_work_no,
                 city_manager_name,
                 item_province_manager_id,
                 item_province_manager_work_no,
                 item_province_manager_name,
                 org_code,
                 org_name,
                 is_copemate_order,
                 channel,
                 channel_name,
                 province_code,
                 province_name,
                 city_code,
                 city_name,
                 city_group_code,
                 city_group_name,
                 city_real,
                 cityjob,
                 province_manager_id,
                 province_manager_work_no,
                 province_manager_name,
                 COUNT(DISTINCT goods_code) AS sales_sku,
                 count(DISTINCT sdt) AS sales_days,
                 sum(sales_value)AS sales_value,
                 sum(sales_qty)AS sales_qty,
                 sum(profit)AS profit,
                 sum(front_profit) AS front_profit,
                 sum(profit)/sum(sales_value) AS profit_rate,
                 sum(CASE
                         WHEN return_flag='X' THEN sales_value
                     END) AS return_amt
   FROM csx_dw.dws_sale_r_d_customer_sale a
   JOIN
     (SELECT business_division_code,
             business_division_name,
             category_small_code,
             purchase_group_code,
             purchase_group_name
      FROM csx_dw.dws_basic_w_a_category_m
      WHERE sdt='current') b ON a.category_small_code=b.category_small_code
   WHERE sdt >= ${hiveconf:s_date} and sdt<=regexp_replace(to_date(${hiveconf:i_edate}),'-','') 
   GROUP BY customer_no,
            customer_name,
            attribute_code,
            `attribute`,
            first_category_code,
            first_category,
            second_category_code,
            second_category,
            third_category_code,
            third_category,
            sales_province_code,
            sales_province,
            sales_name,
            sales_phone,
            supervisor_id,
            supervisor_work_no,
            supervisor_name,
            city_manager_id,
            city_manager_work_no,
            city_manager_name,
            item_province_manager_id,
            item_province_manager_work_no,
            item_province_manager_name,
            org_code,
            org_name,
            is_copemate_order,
            channel,
            channel_name,
            province_code,
            province_name,
            city_code,
            city_name,
            city_group_code,
            city_group_name,
            city_real,
            cityjob,
            province_manager_id,
            province_manager_work_no,
            province_manager_name,
            business_division_code,
            business_division_name,
            purchase_group_code,
            purchase_group_name,
            substr(sdt,1,4)
         )a  ;