drop table `csx_dw.ads_sale_customer_division_level_sales`;
CREATE TABLE `csx_dw.ads_supply_customer_division_level_sales`
	(   
		`sales_year` string COMMENT '销售年份'                   ,
		`sales_months` string COMMENT '销售月份'                  ,
		`layer` string COMMENT '层级 ：1 合计、2采购部、3课组'           ,
		`business_division_code` string COMMENT '采购部编码'      ,
		`business_division_name` string COMMENT '采购部名称'      ,
		`purchase_group_code` string COMMENT '课组编码'          ,
		`purchase_group_name` string COMMENT '课组名称'          ,
		`customer_no` string COMMENT '客户编码'                  ,
		`customer_name` string COMMENT '客户名称'                ,
		`attribute_code` int COMMENT '客户属性编码'                ,
		`attribute` string COMMENT '客户属性名称'                  ,
		`first_category_code` string COMMENT '企业类型编码一级'      ,
		`first_category` string COMMENT '企业类型类型名称一级'         ,
		`second_category_code` string COMMENT '企业类型类型编码二级'   ,
		`second_category` string COMMENT '企业类型类型名称二级'        ,
		`third_category_code` string COMMENT '企业类型类型编码三级'    ,
		`third_category` string COMMENT '企业类型类型名称三级'         ,
		`sales_province_code` string COMMENT '销售省区编码'        ,
		`sales_province` string COMMENT '销售省区名称'             ,
		`is_copemate_order` int COMMENT '是否合伙人（0.否  1.是）'    ,
		`channel` string COMMENT '战报渠道编码'                    ,
		`channel_name` string COMMENT '战报渠道名称'               ,
		`province_code` string COMMENT '战报省区编码'              ,
		`province_name` string COMMENT '战报省区名称'              ,
		`city_code` string COMMENT '战报城市编码'                  ,
		`city_name` string COMMENT '战报城市名称'                  ,
		`city_group_code` string COMMENT '战报城市组编码'           ,
		`city_group_name` string COMMENT '战报城市组名称'           ,
		`city_real` string COMMENT '战报城市组名称'                 ,
		`cityjob` string COMMENT '战报城市组负责人'                  ,
		`province_manager_id` string COMMENT '战报省区负责人'       ,
		`province_manager_work_no` string COMMENT '战报省区负责人工号',
		`province_manager_name` string COMMENT '战报省区负责人姓名'   ,
		`sales_sku`    bigint COMMENT '销售sku'                   ,
		`sales_days`   bigint COMMENT '销售天数'                    ,
		`sales_value`  decimal(36,6) COMMENT '销售额'              ,
		`sales_qty`    decimal(36,6) COMMENT '销量'               ,
		`profit`       decimal(36,6) COMMENT '毛利额'              ,
		`front_profit` decimal(36,6) COMMENT '前端毛利额'            ,
		`profit_rate`  decimal(38,6) COMMENT '毛利率'              ,
		`return_amt`   decimal(36,6) COMMENT '退货额'              ,
		`rank_num`     int COMMENT '销售排名',
		`write_time` TIMESTAMP COMMENT'写入时间'
	)
	COMMENT '客户月销售报表' partitioned BY
	(
		sdt string COMMENT '日期分区,按月分区',`date_m` STRING COMMENT '日期维度 m 月、y 年累计')
	)
	STORED AS parquet 
	--LOCATION 'hdfs://nameservice1/user/hive/warehouse/csx_dw.db/ads_sale_customer_division_level_sales_months'
;
drop table csx_dw.ads_sale_customer_division_level_sales;


SET mapreduce.job.queuename=caishixian;
set hive.exec.dynamic.partition.mode=nonstrict;

SET i_edate = '${START_DATE}';


SET s_date=regexp_replace(to_date(trunc(${hiveconf:i_edate},'YY')),'-','');

-- SELECT ${hiveconf:s_date},substr(regexp_replace(trunc(${hiveconf:i_edate},'YY'),'-',''),1,4) as sales_year,
--         substr(regexp_replace(trunc(${hiveconf:i_edate},'MM'),'-',''),1,6) as sales_months;

-- 计算月至今客户销售
-- 1.合计
-- SHOW
-- CREATE TABLE csx_dw.ads_sale_customer_division_level_sales;
INSERT overwrite table csx_dw.ads_supply_customer_division_level_sales partition(sdt)
SELECT  'm' as date_m,
    sales_year,
        sales_months,
        layer,
       business_division_code,
       business_division_name,
       purchase_group_code,
       purchase_group_name,
       customer_no,
       customer_name,
       attribute_code,
       `attribute`,
       first_category_code,
       first_category,
       second_category_code,
       second_category,
       third_category_code,
       third_category,
       sales_province_code,
       sales_province,
       is_copemate_order,
       channel,
       channel_name,
       province_code,
       province_name,
       city_code,
       city_name,
       city_group_code,
       city_group_name,
       city_real,
       cityjob,
       province_manager_id,
       province_manager_work_no,
       province_manager_name,
       sales_sku,
        sales_days,
       sales_value,
       sales_qty,
       profit,
       front_profit,
      coalesce(profit/sales_value,0) AS profit_rate,
        return_amt,
        rank()over(partition by layer,channel,province_code,sales_months,sales_year order by sales_value desc ) as rank_num,
        current_timestamp() as write_time,
        regexp_replace(${hiveconf:i_edate},'-','')
FROM
  ( SELECT substr(sdt,1,4) as sales_year,
            substr(sdt,1,6) as sales_months,
            '1' AS LAYER,
           '00' AS business_division_code,
           '合计' AS business_division_name,
           '00' AS purchase_group_code,
           '小计'AS purchase_group_name,
           customer_no,
           customer_name,
           attribute_code,
           `attribute`,
           first_category_code,
           first_category,
           second_category_code,
           second_category,
           third_category_code,
           third_category,
           sales_province_code,
           sales_province,
           sales_name,
           sales_phone,
           supervisor_id,
           supervisor_work_no,
           supervisor_name,
           city_manager_id,
           city_manager_work_no,
           city_manager_name,
           item_province_manager_id,
           item_province_manager_work_no,
           item_province_manager_name,
           org_code,
           org_name,
           is_copemate_order,
           channel,
           channel_name,
           province_code,
           province_name,
           city_code,
           city_name,
           city_group_code,
           city_group_name,
           city_real,
           cityjob,
           province_manager_id,
           province_manager_work_no,
           province_manager_name,
           COUNT(DISTINCT goods_code) AS sales_sku,
           count(DISTINCT sdt) AS sales_days,
           sum(sales_value)AS sales_value,
           sum(sales_qty)AS sales_qty,
           sum(profit)AS profit,
           sum(front_profit) AS front_profit,
           sum(profit)/sum(sales_value) AS profit_rate,
           sum(CASE
                   WHEN return_flag='X' THEN sales_value
               END) AS return_amt
   FROM csx_dw.dws_sale_r_d_customer_sale
   WHERE sdt >= ${hiveconf:s_date}
   and sdt<=regexp_replace(to_date(${hiveconf:i_edate}),'-','') 
   GROUP BY customer_no,
            customer_name,
            attribute_code,
            `attribute`,
            first_category_code,
            first_category,
            second_category_code,
            second_category,
            third_category_code,
            third_category,
            sales_province_code,
            sales_province,
            sales_name,
            sales_phone,
            supervisor_id,
            supervisor_work_no,
            supervisor_name,
            city_manager_id,
            city_manager_work_no,
            city_manager_name,
            item_province_manager_id,
            item_province_manager_work_no,
            item_province_manager_name,
            org_code,
            org_name,
            is_copemate_order,
            channel,
            channel_name,
            province_code,
            province_name,
            city_code,
            city_name,
            city_group_code,
            city_group_name,
            city_real,
            cityjob,
            province_manager_id,
            province_manager_work_no,
            province_manager_name,substr(sdt,1,4) ,
            substr(sdt,1,6) 
            --采购级别
UNION ALL
SELECT substr(sdt,1,4) as sales_year,
            substr(sdt,1,6) as sales_months,
            '2' AS LAYER,
                 business_division_code,
                 business_division_name,
                 '00' AS purchase_group_code,
                 '小计'AS purchase_group_name,
                 customer_no,
                 customer_name,
                 attribute_code,
                 `attribute`,
                 first_category_code,
                 first_category,
                 second_category_code,
                 second_category,
                 third_category_code,
                 third_category,
                 sales_province_code,
                 sales_province,
                 sales_name,
                 sales_phone,
                 supervisor_id,
                 supervisor_work_no,
                 supervisor_name,
                 city_manager_id,
                 city_manager_work_no,
                 city_manager_name,
                 item_province_manager_id,
                 item_province_manager_work_no,
                 item_province_manager_name,
                 org_code,
                 org_name,
                 is_copemate_order,
                 channel,
                 channel_name,
                 province_code,
                 province_name,
                 city_code,
                 city_name,
                 city_group_code,
                 city_group_name,
                 city_real,
                 cityjob,
                 province_manager_id,
                 province_manager_work_no,
                 province_manager_name,
                 COUNT(DISTINCT goods_code) AS sales_sku,
                 count(DISTINCT sdt) AS sales_days,
                 sum(sales_value)AS sales_value,
                 sum(sales_qty)AS sales_qty,
                 sum(profit)AS profit,
                 sum(front_profit) AS front_profit,
                 sum(profit)/sum(sales_value) AS profit_rate,
                 sum(CASE
                         WHEN return_flag='X' THEN sales_value
                     END) AS return_amt
   FROM csx_dw.dws_sale_r_d_customer_sale a
   JOIN
     (SELECT business_division_code,
             business_division_name,
             category_small_code
      FROM csx_dw.dws_basic_w_a_category_m
      WHERE sdt='current') b ON a.category_small_code=b.category_small_code
   WHERE sdt >= ${hiveconf:s_date}
   and  sdt<=regexp_replace(to_date(${hiveconf:i_edate}),'-','') 
   GROUP BY customer_no,
            customer_name,
            attribute_code,
            `attribute`,
            first_category_code,
            first_category,
            second_category_code,
            second_category,
            third_category_code,
            third_category,
            sales_province_code,
            sales_province,
            sales_name,
            sales_phone,
            supervisor_id,
            supervisor_work_no,
            supervisor_name,
            city_manager_id,
            city_manager_work_no,
            city_manager_name,
            item_province_manager_id,
            item_province_manager_work_no,
            item_province_manager_name,
            org_code,
            org_name,
            is_copemate_order,
            channel,
            channel_name,
            province_code,
            province_name,
            city_code,
            city_name,
            city_group_code,
            city_group_name,
            city_real,
            cityjob,
            province_manager_id,
            province_manager_work_no,
            province_manager_name,
            business_division_code,
            business_division_name,substr(sdt,1,4),
            substr(sdt,1,6) 
-- 课组级别
UNION ALL 
SELECT 
substr(sdt,1,4) as sales_year,
            substr(sdt,1,6) as sales_months,
            '3' AS LAYER,
                 business_division_code,
                 business_division_name,
                 purchase_group_code,
                 purchase_group_name,
                 customer_no,
                 customer_name,
                 attribute_code,
                 `attribute`,
                 first_category_code,
                 first_category,
                 second_category_code,
                 second_category,
                 third_category_code,
                 third_category,
                 sales_province_code,
                 sales_province,
                 sales_name,
                 sales_phone,
                 supervisor_id,
                 supervisor_work_no,
                 supervisor_name,
                 city_manager_id,
                 city_manager_work_no,
                 city_manager_name,
                 item_province_manager_id,
                 item_province_manager_work_no,
                 item_province_manager_name,
                 org_code,
                 org_name,
                 is_copemate_order,
                 channel,
                 channel_name,
                 province_code,
                 province_name,
                 city_code,
                 city_name,
                 city_group_code,
                 city_group_name,
                 city_real,
                 cityjob,
                 province_manager_id,
                 province_manager_work_no,
                 province_manager_name,
                 COUNT(DISTINCT goods_code) AS sales_sku,
                 count(DISTINCT sdt) AS sales_days,
                 sum(sales_value)AS sales_value,
                 sum(sales_qty)AS sales_qty,
                 sum(profit)AS profit,
                 sum(front_profit) AS front_profit,
                 sum(profit)/sum(sales_value) AS profit_rate,
                 sum(CASE
                         WHEN return_flag='X' THEN sales_value
                     END) AS return_amt
   FROM csx_dw.dws_sale_r_d_customer_sale a
   JOIN
     (SELECT business_division_code,
             business_division_name,
             category_small_code,
             purchase_group_code,
             purchase_group_name
      FROM csx_dw.dws_basic_w_a_category_m
      WHERE sdt='current') b ON a.category_small_code=b.category_small_code
   WHERE sdt >= ${hiveconf:s_date} and sdt<=regexp_replace(to_date(${hiveconf:i_edate}),'-','') 
   GROUP BY customer_no,
            customer_name,
            attribute_code,
            `attribute`,
            first_category_code,
            first_category,
            second_category_code,
            second_category,
            third_category_code,
            third_category,
            sales_province_code,
            sales_province,
            sales_name,
            sales_phone,
            supervisor_id,
            supervisor_work_no,
            supervisor_name,
            city_manager_id,
            city_manager_work_no,
            city_manager_name,
            item_province_manager_id,
            item_province_manager_work_no,
            item_province_manager_name,
            org_code,
            org_name,
            is_copemate_order,
            channel,
            channel_name,
            province_code,
            province_name,
            city_code,
            city_name,
            city_group_code,
            city_group_name,
            city_real,
            cityjob,
            province_manager_id,
            province_manager_work_no,
            province_manager_name,
            business_division_code,
            business_division_name,
            purchase_group_code,
            purchase_group_name,substr(sdt,1,4),
            substr(sdt,1,6) )a
          ;
INSERT into table csx_dw.ads_supply_customer_division_level_sales partition(sdt)
SELECT  
'y' date_m,
    sales_year,
        sales_months,
        layer,
       business_division_code,
       business_division_name,
       purchase_group_code,
       purchase_group_name,
       customer_no,
       customer_name,
       attribute_code,
       `attribute`,
       first_category_code,
       first_category,
       second_category_code,
       second_category,
       third_category_code,
       third_category,
       sales_province_code,
       sales_province,
       is_copemate_order,
       channel,
       channel_name,
       province_code,
       province_name,
       city_code,
       city_name,
       city_group_code,
       city_group_name,
       city_real,
       cityjob,
       province_manager_id,
       province_manager_work_no,
       province_manager_name,
       sales_sku,
        sales_days,
       sales_value,
       sales_qty,
       profit,
       front_profit,
      coalesce(profit/sales_value,0) AS profit_rate,
        return_amt,
        rank()over(partition by layer,channel,province_code,sales_months,sales_year order by sales_value desc ) as rank_num,
        current_timestamp() as write_time,
        regexp_replace(${hiveconf:i_edate},'-','')
FROM
  ( SELECT substr(sdt,1,4) as sales_year,
            '' as sales_months,
            '1' AS LAYER,
           '00' AS business_division_code,
           '合计' AS business_division_name,
           '00' AS purchase_group_code,
           '小计'AS purchase_group_name,
           customer_no,
           customer_name,
           attribute_code,
           `attribute`,
           first_category_code,
           first_category,
           second_category_code,
           second_category,
           third_category_code,
           third_category,
           sales_province_code,
           sales_province,
           sales_name,
           sales_phone,
           supervisor_id,
           supervisor_work_no,
           supervisor_name,
           city_manager_id,
           city_manager_work_no,
           city_manager_name,
           item_province_manager_id,
           item_province_manager_work_no,
           item_province_manager_name,
           org_code,
           org_name,
           is_copemate_order,
           channel,
           channel_name,
           province_code,
           province_name,
           city_code,
           city_name,
           city_group_code,
           city_group_name,
           city_real,
           cityjob,
           province_manager_id,
           province_manager_work_no,
           province_manager_name,
           COUNT(DISTINCT goods_code) AS sales_sku,
           count(DISTINCT sdt) AS sales_days,
           sum(sales_value)AS sales_value,
           sum(sales_qty)AS sales_qty,
           sum(profit)AS profit,
           sum(front_profit) AS front_profit,
           sum(profit)/sum(sales_value) AS profit_rate,
           sum(CASE
                   WHEN return_flag='X' THEN sales_value
               END) AS return_amt
   FROM csx_dw.dws_sale_r_d_customer_sale
   WHERE sdt >= ${hiveconf:s_date}
   and sdt<=regexp_replace(to_date(${hiveconf:i_edate}),'-','') 
   GROUP BY customer_no,
            customer_name,
            attribute_code,
            `attribute`,
            first_category_code,
            first_category,
            second_category_code,
            second_category,
            third_category_code,
            third_category,
            sales_province_code,
            sales_province,
            sales_name,
            sales_phone,
            supervisor_id,
            supervisor_work_no,
            supervisor_name,
            city_manager_id,
            city_manager_work_no,
            city_manager_name,
            item_province_manager_id,
            item_province_manager_work_no,
            item_province_manager_name,
            org_code,
            org_name,
            is_copemate_order,
            channel,
            channel_name,
            province_code,
            province_name,
            city_code,
            city_name,
            city_group_code,
            city_group_name,
            city_real,
            cityjob,
            province_manager_id,
            province_manager_work_no,
            province_manager_name,substr(sdt,1,4)
            --采购级别
UNION ALL
SELECT substr(sdt,1,4) as sales_year,
            '' as sales_months,
            '2' AS LAYER,
                 business_division_code,
                 business_division_name,
                 '00' AS purchase_group_code,
                 '小计'AS purchase_group_name,
                 customer_no,
                 customer_name,
                 attribute_code,
                 `attribute`,
                 first_category_code,
                 first_category,
                 second_category_code,
                 second_category,
                 third_category_code,
                 third_category,
                 sales_province_code,
                 sales_province,
                 sales_name,
                 sales_phone,
                 supervisor_id,
                 supervisor_work_no,
                 supervisor_name,
                 city_manager_id,
                 city_manager_work_no,
                 city_manager_name,
                 item_province_manager_id,
                 item_province_manager_work_no,
                 item_province_manager_name,
                 org_code,
                 org_name,
                 is_copemate_order,
                 channel,
                 channel_name,
                 province_code,
                 province_name,
                 city_code,
                 city_name,
                 city_group_code,
                 city_group_name,
                 city_real,
                 cityjob,
                 province_manager_id,
                 province_manager_work_no,
                 province_manager_name,
                 COUNT(DISTINCT goods_code) AS sales_sku,
                 count(DISTINCT sdt) AS sales_days,
                 sum(sales_value)AS sales_value,
                 sum(sales_qty)AS sales_qty,
                 sum(profit)AS profit,
                 sum(front_profit) AS front_profit,
                 sum(profit)/sum(sales_value) AS profit_rate,
                 sum(CASE
                         WHEN return_flag='X' THEN sales_value
                     END) AS return_amt
   FROM csx_dw.dws_sale_r_d_customer_sale a
   JOIN
     (SELECT business_division_code,
             business_division_name,
             category_small_code
      FROM csx_dw.dws_basic_w_a_category_m
      WHERE sdt='current') b ON a.category_small_code=b.category_small_code
   WHERE sdt >= ${hiveconf:s_date}
   and  sdt<=regexp_replace(to_date(${hiveconf:i_edate}),'-','') 
   GROUP BY customer_no,
            customer_name,
            attribute_code,
            `attribute`,
            first_category_code,
            first_category,
            second_category_code,
            second_category,
            third_category_code,
            third_category,
            sales_province_code,
            sales_province,
            sales_name,
            sales_phone,
            supervisor_id,
            supervisor_work_no,
            supervisor_name,
            city_manager_id,
            city_manager_work_no,
            city_manager_name,
            item_province_manager_id,
            item_province_manager_work_no,
            item_province_manager_name,
            org_code,
            org_name,
            is_copemate_order,
            channel,
            channel_name,
            province_code,
            province_name,
            city_code,
            city_name,
            city_group_code,
            city_group_name,
            city_real,
            cityjob,
            province_manager_id,
            province_manager_work_no,
            province_manager_name,
            business_division_code,
            business_division_name,
            substr(sdt,1,4)
-- 课组级别
UNION ALL 
SELECT 
        substr(sdt,1,4) as sales_year,
           '' as sales_months,
            '3' AS LAYER,
                 business_division_code,
                 business_division_name,
                 purchase_group_code,
                 purchase_group_name,
                 customer_no,
                 customer_name,
                 attribute_code,
                 `attribute`,
                 first_category_code,
                 first_category,
                 second_category_code,
                 second_category,
                 third_category_code,
                 third_category,
                 sales_province_code,
                 sales_province,
                 sales_name,
                 sales_phone,
                 supervisor_id,
                 supervisor_work_no,
                 supervisor_name,
                 city_manager_id,
                 city_manager_work_no,
                 city_manager_name,
                 item_province_manager_id,
                 item_province_manager_work_no,
                 item_province_manager_name,
                 org_code,
                 org_name,
                 is_copemate_order,
                 channel,
                 channel_name,
                 province_code,
                 province_name,
                 city_code,
                 city_name,
                 city_group_code,
                 city_group_name,
                 city_real,
                 cityjob,
                 province_manager_id,
                 province_manager_work_no,
                 province_manager_name,
                 COUNT(DISTINCT goods_code) AS sales_sku,
                 count(DISTINCT sdt) AS sales_days,
                 sum(sales_value)AS sales_value,
                 sum(sales_qty)AS sales_qty,
                 sum(profit)AS profit,
                 sum(front_profit) AS front_profit,
                 sum(profit)/sum(sales_value) AS profit_rate,
                 sum(CASE
                         WHEN return_flag='X' THEN sales_value
                     END) AS return_amt
   FROM csx_dw.dws_sale_r_d_customer_sale a
   JOIN
     (SELECT business_division_code,
             business_division_name,
             category_small_code,
             purchase_group_code,
             purchase_group_name
      FROM csx_dw.dws_basic_w_a_category_m
      WHERE sdt='current') b ON a.category_small_code=b.category_small_code
   WHERE sdt >= ${hiveconf:s_date} and sdt<=regexp_replace(to_date(${hiveconf:i_edate}),'-','') 
   GROUP BY customer_no,
            customer_name,
            attribute_code,
            `attribute`,
            first_category_code,
            first_category,
            second_category_code,
            second_category,
            third_category_code,
            third_category,
            sales_province_code,
            sales_province,
            sales_name,
            sales_phone,
            supervisor_id,
            supervisor_work_no,
            supervisor_name,
            city_manager_id,
            city_manager_work_no,
            city_manager_name,
            item_province_manager_id,
            item_province_manager_work_no,
            item_province_manager_name,
            org_code,
            org_name,
            is_copemate_order,
            channel,
            channel_name,
            province_code,
            province_name,
            city_code,
            city_name,
            city_group_code,
            city_group_name,
            city_real,
            cityjob,
            province_manager_id,
            province_manager_work_no,
            province_manager_name,
            business_division_code,
            business_division_name,
            purchase_group_code,
            purchase_group_name,
            substr(sdt,1,4)
         )a  ;