-- 招投标表结构
create  table ods_w_d_bid_collection_import(
id bigint not null auto_increment comment 'id',
bid_month varchar(64) comment'投标月份',
bid_update_date varchar(64) comment'更新日期',
business_date varchar(64) comment'获得商机日期',
registration_deadline varchar(64) comment'报名截止日期',
registration_available  varchar(64) comment'是否报名',
bid_before_audit varchar(64) comment'标前审核',
out_audit varchar(64) comment'出标审核',
bid_date varchar(64) comment'投标日期',
business_leader varchar(64) comment'商机负责人 ',
business_mentor varchar(64) comment'商机指导人',
bid_leader varchar(64) comment'投标负责人',
city_name varchar(64) comment'城市',
city_name2 varchar(64) comment'城市一',
industry_name varchar(64) comment'行业',
category_name varchar(64) comment'品类',
project_name varchar(64) comment'项目名称',
project_code varchar(64) comment'项目编号',
business_no varchar(64) comment'商机号',
purchasing_name varchar(64) comment'采购人',
bid_company_telephone varchar(64) comment'招标公司及电话',
bid_amount varchar(64) comment'标的金额',
packet_count varchar(64) comment'最大可中包数/总包数',
max_bid_amount varchar(64) comment'最大可中标金额',
supply_period varchar(64) comment'供应期限（月）',
cooperation_type varchar(64) comment'合作类型',
blind_bid varchar(64) comment'盲投/销售先行',
new_old_customer varchar(64) comment'新老客',
cooperation_if varchar(64) comment'是否合作',
history_cooperation_type varchar(64) comment'历史合作业务类型',
cooperation_forms varchar(64) comment'合作形式',
customer_infor varchar(64) comment'基本情况备注',
bid_company_name varchar(64) comment'投标主体',
is_bid varchar(64) comment'是否投标',
reason varchar(64) comment'原因分析（大类）',
specific_reason varchar(64) comment'具体原因',
is_public varchar(64) comment'是否公示',
bid_result varchar(64) comment'中标结果',
public_date varchar(64) comment'公示结果日期/中标日期',
outbid_amount varchar(64) comment'中标金额',
lower_rate varchar(64) comment'下浮率',
contract_amount varchar(64) comment'合同金额',
contract_period varchar(64) comment'合同期限',
month_purchase_amount varchar(64) comment'月采购金额',
project_results varchar(64) comment'项目结果',
remark varchar(64) comment'备注',
bid_condition varchar(64) comment'开标情况',
update_time timestamp comment '更新时间'
)


'W0A7','W0X2','W0Z9','W0A6','W0Q2','W0A3','W0P8','W0Q9','W0A5','W0R9','W0AS','W0N0','W0W7','W0F4','W0A8','W0J2','W0K6','W0L3','W0AH','W0K1','WA96','W0BK','W0A2','W0BR','W0BH'