CREATE TABLE `csx_tmp.ads_sale_r_d_zone_sales_fr`(
  `level_id` string COMMENT '展示层级，1 明细、2 渠道汇总、3总计', 
  `sales_months` string COMMENT '销售月份', 
  `zone_id` string COMMENT '战区编码', 
  `zone_name` string COMMENT '战区名称', 
  `channel_code` string COMMENT '渠道编码', 
  `channel_name` string COMMENT '渠道', 
  `province_code` string COMMENT '省区编码', 
  `province_name` string COMMENT '省区名称', 
  `daily_plan_sale` decimal(26,6) COMMENT '昨日计划销售额', 
  `daily_sales_value` decimal(26,6) COMMENT '昨日销售额', 
  `daily_sale_fill_rate` decimal(26,6) COMMENT '日销售达成率', 
  `last_week_daily_sales` decimal(26,6) COMMENT '上周同日销售额 当前日期-7', 
  `daily_sale_growth_rate` decimal(26,6) COMMENT '昨日环比增长率', 
  `daily_plan_profit` decimal(26,6) COMMENT '昨日销售毛利计划', 
  `daily_profit` decimal(26,6) COMMENT '昨日毛利额', 
  `daily_profit_fill_rate` decimal(26,6) COMMENT '昨日毛利额完成率', 
  `daily_profit_rate` decimal(26,6) COMMENT '昨日毛利率', 
  `daily_negative_profit` decimal(26,6) COMMENT '负毛利金额', 
  `daily_often_cust_sale` decimal(26,6) COMMENT '昨日老客销售额，首次成交未在本月', 
  `daily_new_cust_sale` decimal(26,6) COMMENT '昨日新额销售额，首次成交在本月', 
  `daily_sale_cust_num` bigint COMMENT '昨日成交数', 
  `month_plan_sale` decimal(26,6) COMMENT '月至今销售预算', 
  `month_sale_value` decimal(26,6) COMMENT '月至今销售额', 
  `real_month_sale_value` decimal(26,6) COMMENT '月至今销售额不含批发内购', 
  `real_month_sale_fill_rate` decimal(26,6) COMMENT '月至今销售额不含批发内购', 
  `month_sale_fill_rate` decimal(26,6) COMMENT '月至今销售达成率', 
  `last_month_sale` decimal(26,6) COMMENT '月环比销售额', 
  `mom_sale_growth_rate` decimal(26,6) COMMENT '月环比增长率', 
  `month_plan_profit` decimal(26,6) COMMENT '月度毛利计划', 
  `month_profit` decimal(26,6) COMMENT '月毛利额', 
  `month_profit_fill_rate` decimal(26,6) COMMENT '月度毛利完成率', 
  `month_profit_rate` decimal(26,6) COMMENT '月毛利率', 
  `month_negative_profit` decimal(26,6) COMMENT '负毛利额', 
  `month_often_cust_sale` decimal(26,6) COMMENT '月老客销售额', 
  `month_new_cust_sale` decimal(26,6) COMMENT '新客销售额', 
  `month_sale_cust_num` bigint COMMENT '成交数', 
  `last_months_daily_sale` decimal(26,6) COMMENT '上月同日销售额', 
  `update_time` timestamp COMMENT '更新时间戳')
COMMENT '战区月累计销售跟踪'
PARTITIONED BY ( 
  `sdt` string COMMENT '按日分区')
;





CREATE TABLE `csx_tmp.ads_sale_r_d_city_sales_fr`(
  `level_id` string COMMENT '等级：1 城市汇总、2、省区汇总、3、省区全渠道、4、大区全渠道汇总', 
  `sales_months` string COMMENT '销售月份', 
  `zone_id` string COMMENT '战区编码', 
  `zone_name` string COMMENT '战区名称', 
  `channel_code` string COMMENT '渠道编码', 
  `channel_name` string COMMENT '渠道', 
  `province_code` string COMMENT '省区编码', 
  `province_name` string COMMENT '省区名称', 
  `city_group_code` string COMMENT '城市编码', 
  `city_group_name` string COMMENT '城市组名称', 
  `daily_plan_sale` decimal(26,6) COMMENT '昨日计划销售额', 
  `daily_sales_value` decimal(26,6) COMMENT '昨日销售额', 
  `daily_sale_fill_rate` decimal(26,6) COMMENT '日销售达成率', 
  `last_week_daily_sales` decimal(26,6) COMMENT '上周同日销售额 当前日期-7', 
  `daily_sale_growth_rate` decimal(26,6) COMMENT '昨日环比增长率', 
  `daily_plan_profit` decimal(26,6) COMMENT '昨日销售毛利计划', 
  `daily_profit` decimal(26,6) COMMENT '昨日毛利额', 
  `daily_profit_fill_rate` decimal(26,6) COMMENT '昨日毛利额完成率', 
  `daily_profit_rate` decimal(26,6) COMMENT '昨日毛利率', 
  `daily_negative_profit` decimal(26,6) COMMENT '负毛利金额', 
  `daily_often_cust_sale` decimal(26,6) COMMENT '昨日老客销售额，首次成交未在本月', 
  `daily_new_cust_sale` decimal(26,6) COMMENT '昨日新额销售额，首次成交在本月', 
  `daily_sale_cust_num` bigint COMMENT '昨日成交数', 
  `month_plan_sale` decimal(26,6) COMMENT '月至今销售预算', 
  `month_sale_value` decimal(26,6) COMMENT '月至今销售额', 
    `real_month_sale_value` decimal(26,6) COMMENT '月至今销售额不含批发内购', 
  `real_month_sale_fill_rate` decimal(26,6) COMMENT '月至今销售额不含批发内购', 
  `month_sale_fill_rate` decimal(26,6) COMMENT '月至今销售达成率', 
  `last_month_sale` decimal(26,6) COMMENT '月环比销售额', 
  `mom_sale_growth_rate` decimal(26,6) COMMENT '月环比增长率', 
  `month_plan_profit` decimal(26,6) COMMENT '月度毛利计划', 
  `month_profit` decimal(26,6) COMMENT '月毛利额', 
  `month_profit_fill_rate` decimal(26,6) COMMENT '月度毛利完成率', 
  `month_profit_rate` decimal(26,6) COMMENT '月毛利率', 
  `month_negative_profit` decimal(26,6) COMMENT '负毛利额', 
  `month_often_cust_sale` decimal(26,6) COMMENT '月老客销售额', 
  `month_new_cust_sale` decimal(26,6) COMMENT '新客销售额', 
  `month_sale_cust_num` bigint COMMENT '成交数', 
  `last_months_daily_sale` decimal(26,6) COMMENT '上月同日销售额', 
  `update_time` timestamp COMMENT '更新时间戳')
COMMENT '城市组销售看板'
PARTITIONED BY ( 
  `sdt` string COMMENT '日期分区')
;
