-- 蔬菜入库21年  temp_order_entry
SELECT mon,
       sales_region_code,
       sales_region_name,
       purchase_org,
       province_code,
       province_name,
       city_code,
       city_name,
       purpose,
       purpose_name,
       source_type,
       source_type_name,
       dc_code,
       shop_name,
       goods_code,
       goods_name,
       spu_goods_code,
       spu_goods_name,
       brand_name,
       classify_large_code,
       classify_large_name,
       classify_middle_code,
       classify_middle_name,
       classify_small_code,
       classify_small_name,
       department_id,
       department_name,
       supplier_code,
       vendor_name,
       supplier_type,
       supplier_type_name,
       sum(qty) qty,
       sum(amt) amt,
       sum(shipp_qty) shipp_qty,
       sum(shipp_amt) shipp_amt,
       sum(net_qty) net_qty,
       sum(net_amt) net_amt,
       product_level,
       product_level_name
FROM csx_tmp.temp_order_entry
WHERE department_id='H03'
  AND MON BETWEEN '202101' AND '202109'
  GROUP BY mon,
       sales_region_code,
       sales_region_name,
       purchase_org,
       province_code,
       province_name,
       city_code,
       city_name,
       purpose,
       purpose_name,
       source_type,
       source_type_name,
       dc_code,
       shop_name,
       goods_code,
       goods_name,
       spu_goods_code,
       spu_goods_name,
       brand_name,
       classify_large_code,
       classify_large_name,
       classify_middle_code,
       classify_middle_name,
       classify_small_code,
       classify_small_name,
       department_id,
       department_name,
       supplier_code,
       vendor_name,
       supplier_type,
       supplier_type_name,
        product_level,
       product_level_name