--新逻辑调整 信控预测20211110 建表语句
CREATE TABLE `csx_dw.report_fr_crm_r_d_credit_rating_scar`(
  `sflag` string COMMENT '客户类型', 
  `hkont` string COMMENT '科目', 
  `account_name` string COMMENT '科目名称', 
  `comp_code` string COMMENT '帐龄公司代码', 
  `comp_name` string COMMENT '帐龄公司代码名称', 
  `company_code` string COMMENT 'CRM公司代码', 
  `sale_company_code` string COMMENT '销售公司代码', 
  `sales_province_code` string COMMENT '省区编码', 
  `sales_province` string COMMENT '省区名称', 
  `sales_city_code` string COMMENT '城市编码', 
  `sales_city` string COMMENT '城市名称', 
  `province_code` string COMMENT '客户归属省区', 
  `province_name` string COMMENT '客户归属省区名称', 
  `city_code` string COMMENT '客户归属城市', 
  `city_name` string COMMENT '客户归属城市名称', 
  `sales_name` string COMMENT '销售员', 
  `work_no` string COMMENT '工号', 
  `customer_no` string COMMENT '客户编码', 
  `customer_name` string COMMENT '客户名称', 
  `attribute` string COMMENT '客户属性', 
  `credit_limit` string COMMENT '固定额度', 
  `temp_credit_limit` string COMMENT '临时额度', 
  `channel` string COMMENT '分销渠道', 
  `first_category` string COMMENT '一级性质', 
  `second_category` string COMMENT '二级性质', 
  `third_category` string COMMENT '三级性质', 
  `sign_date` string COMMENT '签约日期', 
  `zterm` string COMMENT '账期类型', 
  `diff` string COMMENT '帐期时长', 
  `ac_wdq` decimal(26,6) COMMENT '未到期账款', 
  `ac_15d` decimal(26,6) COMMENT '逾期1-15天', 
  `ac_30d` decimal(26,6) COMMENT '逾期16-30天', 
  `ac_60d` decimal(26,6) COMMENT '逾期31-60天', 
  `ac_90d` decimal(26,6) COMMENT '逾期61-90天', 
  `ac_120d` decimal(26,6) COMMENT '逾期91-120天', 
  `ac_180d` decimal(26,6) COMMENT '逾期121-180天', 
  `ac_365d` decimal(26,6) COMMENT '逾期181-365天', 
  `ac_2y` decimal(26,6) COMMENT '逾期1-2年', 
  `ac_3y` decimal(26,6) COMMENT '逾期2-3年', 
  `ac_over3y` decimal(26,6) COMMENT '逾期3年以上', 
  `ac_all` decimal(26,6) COMMENT '应收账款统计', 
  `overdue_account` decimal(26,6) COMMENT '逾期账款统计', 
  `use_ac_all` decimal(26,6) COMMENT '已使用额度', 
  `avg_sale` decimal(26,6) COMMENT '过去30个自然日日均销售', 
  `diff_01` string COMMENT '账期', 
  `index_data` string COMMENT '转换', 
  `unuse_ac` decimal(26,6) COMMENT '未使用额度', 
  `new_credit_limit` decimal(26,6) COMMENT '重新计算的信控固定额度', 
  `future_amount` decimal(26,6) COMMENT '未来信控额度', 
  `surplus_credit` decimal(26,6) COMMENT '剩余信控', 
  `credit_limit1` decimal(26,6) COMMENT '新调整信控额度', 
  `min_sdt` string COMMENT '首单日期', 
  `change_type` string COMMENT '是否调整')
COMMENT 'CRM信控预测新逻辑调整'
PARTITIONED BY ( 
  `sdt` string COMMENT '日期分区') 
STORED AS parquet 
  