CREATE TABLE `csx_dw.provinces_kanban`(
  `type` string COMMENT '类型', 
  `months` string COMMENT '销售月份', 
  `province_code` string COMMENT '省区编码', 
  `province_name` string COMMENT '省区名称', 
  `workshop_code` string COMMENT '车间编码/部类编码/渠道', 
  `workshop_name` string COMMENT '车间编码/部类编码/渠道名称', 
  `sale_sku` decimal(26,6) COMMENT '销售SKU', 
  `all_sku` decimal(26,6) COMMENT '总SKU', 
  `pin_rate` decimal(26, 6) COMMENT '动销率=销售SKU/总SKU', 
  day_sale decimal(26, 6) COMMENT '昨日销售额',
  day_profit decimal(26, 6) COMMENT '昨日毛利额',
  day_profit_rate decimal(26, 6) COMMENT '昨日毛利率',
  `sale` decimal(26,6) COMMENT '销售额', 
  `profit` decimal(26,6) COMMENT '毛利额', 
  `profit_rate` decimal(26,6) COMMENT '毛利率', 
  `mom_sale` decimal(26,6) COMMENT '环期销售额', 
  `mom_profit` decimal(26,6) COMMENT '环期毛利额', 
  `mom_profit_rate` decimal(26,6) COMMENT '环期毛利率', 
  `yoy_sale` decimal(26,6) COMMENT '同期销售额', 
  `yoy_profit` decimal(26,6) COMMENT '同期毛利额', 
  `yoy_profit_rate` decimal(26,6) COMMENT '同期毛利率', 
  `sale_ring_ratio` decimal(26,6) COMMENT '销售环比增长率', 
  `profit_ring_ratio` decimal(26,6) COMMENT '毛利环比长率', 
  `mom_gross_rate_diff` decimal(26,6) COMMENT '毛利率环期率差', 
  `sale_yoy_ratio` decimal(26,6) COMMENT '销售同比增长率', 
  `profit_yoy_ratio` decimal(26,6) COMMENT '毛利同比增长率', 
  `yoy_gross_rate_diff` decimal(26,6) COMMENT '毛利率同比率差', 
  `final_amt` decimal(26,6) COMMENT '期间库存额', 
  `period_qty` decimal(26,6) COMMENT '期末库存量', 
  `period_amt` decimal(26,6) COMMENT '期末库存额', 
  `day_turnover` decimal(26,6) COMMENT '周转天数', 
  `negative_sku` decimal(26,6) COMMENT '负库存SKU', 
  negative_value decimal(26,6) comment '负库存金额',
  `receive_amt` decimal(26,6) COMMENT '入库金额', 
  `shop_dept_cust` decimal(26,6) COMMENT '销售商超数', 
  `big_dept_cust` decimal(26,6) COMMENT '销售大数', 
  `sale_cust_ratio` decimal(26,6) COMMENT '大数占比 销售数/大总数', 
  `big_cust` decimal(26,6) COMMENT '大总数', 
  `mom_big_cust` decimal(26,6) COMMENT '环期数',
  reality_receive_qty decimal(26,6) COMMENT '实际产量物料计划使用数量',
  fact_qty	decimal(26,6) COMMENT '原料数量（领料-退料）即：实际产量物料计划使用数量（reality_receive_qty/fact_qty为出品率,1-出品率为损耗率）',
  fact_rate decimal(26,6) COMMENT 'reality_receive_qty/fact_qty出品率',
  transfer_qty decimal(26,6) comment '调拨出库数量',
  transfer_amt decimal(26,6) comment '调拨出库金额'
)
COMMENT '省区销售看板'
PARTITIONED BY ( `sdt` string COMMENT '日期分区')
STORED AS parquet ;