CREATE TABLE `csx_dw.dws_sale_r_d_customer_sale`
	(
		`dc_code` string COMMENT '库存dc 编码'                                                       ,
		`dc_name` string COMMENT '库存dc 名称'                                                       ,
		`perform_dc_code` string COMMENT '履约dc编码'                                                ,
		`perform_dc_name` string COMMENT '履约dc名称'                                                ,
		`sap_dc_code` string COMMENT 'sap系统dc编码'                                                 ,
		`sap_dc_name` string COMMENT 'sap系统dc名称'                                                 ,
		`dc_company_code` string COMMENT 'DC所属公司代码'                                              ,
		`dc_company_name` string COMMENT 'DC所属公司名称'                                              ,
		`dc_province_code` string COMMENT 'DC所在省区编码'                                             ,
		`dc_province_name` string COMMENT 'DC所在省区名称'                                             ,
		`dc_city_code` string COMMENT 'DC所在城市编码'                                                 ,
		`dc_city_name` string COMMENT 'DC所在城市名称'                                                 ,
		`dc_address` string COMMENT 'DC所在地址'                                                     ,
		`customer_no` string COMMENT '编号'                                                      ,
		`customer_name` string COMMENT '名称'                                                    ,
		`child_customer_no` string COMMENT '子编码'                                               ,
		`child_customer_name` string COMMENT '子名称'                                             ,
		`item_channel_code` string COMMENT 'item渠道编号-1.大 2.商超 4.大宗 5.供应链(食百) 6.供应链(食百) 8.其他'   ,
		`item_channel` string COMMENT 'item销售渠道,B端、M端、S端、大宗,BBC'                                 ,
		`first_category` string COMMENT '一级分类'                                                 ,
		`first_category_code` string COMMENT '一级分类code'                                        ,
		`second_category` string COMMENT '二级分类'                                                ,
		`second_category_code` string COMMENT '二级分类code'                                       ,
		`third_category` string COMMENT '三级分类'                                                 ,
		`third_category_code` string COMMENT '三级分类code'                                        ,
		`attribute_code` int COMMENT '属性 1:日配 2:福利 3:贸易 4:战略 5:合伙人'                  ,
		`attribute` string COMMENT '属性 1:日配 2:福利 3:贸易 4:战略 5:合伙人'                    ,
		`sales_province` string COMMENT '所属销售省区'                                               ,
		`sales_province_code` string COMMENT '所属销售省区code'                                      ,
		`sales_city` string COMMENT '所属销售城市'                                                   ,
		`sales_city_code` string COMMENT '所属销售城市code'                                          ,
		`sign_time` string COMMENT '签约时间'                                                      ,
		`sign_date` string COMMENT '签约日期'                                                      ,
		`sign_week` string COMMENT '签约周'                                                       ,
		`sign_month` string COMMENT '签约月'                                                      ,
		`item_province_name` string COMMENT 'item地理省区'                                         ,
		`item_province_code` string COMMENT 'item地理省区code'                                     ,
		`item_city_name` string COMMENT 'item地理城市'                                             ,
		`item_city_code` string COMMENT 'item地理城市编码'                                           ,
		`payment_terms` string COMMENT '账期类型'                                                  ,
		`payment_days` string COMMENT '账期'                                                       ,
		`phone` string COMMENT '手机号'                                                           ,
		`sales_name` string COMMENT '业务员名称'                                                      ,
		`sales_id` string COMMENT '业务员id'                                                        ,
		`work_no` string COMMENT '业务员工号'                                                         ,
		`sales_phone` string COMMENT '业务员手机号'                                                    ,
		`supervisor_name` string COMMENT '主管名称'                                                  ,
		`supervisor_id` string COMMENT '主管id'                                                    ,
		`supervisor_work_no` string COMMENT '主管工号'                                               ,
		`city_manager_name` string COMMENT '城市主管'                                                ,
		`city_manager_id` string COMMENT '城市主管id'                                                ,
		`city_manager_work_no` string COMMENT '城市主管工号'                                           ,
		`item_province_manager_name` string COMMENT 'item省区主管名称'                                 ,
		`item_province_manager_id` string COMMENT 'item省区主管id'                                   ,
		`item_province_manager_work_no` string COMMENT 'item省区主管工号'                              ,
		`org_name` string COMMENT '业务员所属组织名称'                                                    ,
		`org_code` string COMMENT '业务员所属组织编码'                                                    ,
		`order_time` string COMMENT '下单时间'                                                       ,
		`origin_sales_date` string COMMENT '原单销售日期，正向单则为正常销售日期，退单则为该退单所对应的正向单销售日期'               ,
		`sales_date` string COMMENT '销售日期'                                                       ,
		`merchant_type` string COMMENT '（企业购）商家业务类型，比如：HQBULK：红旗大宗，MANUAL_BULK：手工单，MAPP_BULK：小程序',
		`sales_channel` string COMMENT '分销渠道'                                                    ,
		`sales_channel_name` string COMMENT '分销渠道名称'                                             ,
		`promotion_code` string COMMENT '促销编码'                                                   ,
		`goods_code` string COMMENT '商品编码(业务主键) '                                                ,
		`goods_name` string COMMENT '商品名称'                                                       ,
		`self_product_name` string COMMENT '自建商品名称'                                              ,
		`area_product_name` string COMMENT '商品区域名称'                                              ,
		`bar_code` string COMMENT '条码'                                                           ,
		`unit` string COMMENT '基本计量单位'                                                           ,
		`division_name` string COMMENT 'sap部类名称'                                                 ,
		`division_code` string COMMENT 'sap部类编码'                                                 ,
		`category_large_name` string COMMENT 'sap大类名称'                                           ,
		`category_large_code` string COMMENT 'sap大类编码'                                           ,
		`category_middle_name` string COMMENT 'sap中类名称'                                          ,
		`category_middle_code` string COMMENT 'sap中类编码'                                          ,
		`category_small_name` string COMMENT 'sap小类名称'                                           ,
		`category_small_code` string COMMENT 'sap小类编码'                                           ,
		`brand` string COMMENT '品牌'                                                              ,
		`brand_name` string COMMENT '品牌名称'                                                       ,
		`department_name` string COMMENT '课组名称'                                                  ,
		`department_code` string COMMENT '课组编码'                                                  ,
		`origin_order_no` string COMMENT '原始订单号，如果是退单，单号是原始下单单号，如果是正向单, 则为订单号'                   ,
		`order_no` string COMMENT '订单号'                                                          ,
		`sap_doc_number` string COMMENT 'sap订单号'                                                 ,
		`report_price`            int COMMENT '报价标识：0：未在中台报价，1：在中台报价'                                       ,
		`cost_price`              decimal(26,6) COMMENT '商品进价（成本价）'                                         ,
		`purchase_price`          decimal(26,6) COMMENT '采购价格'                                              ,
		`middle_office_price`     decimal(26,6) COMMENT '中台报价'                                              ,
		`sales_price`             decimal(26,6) COMMENT '正常含税售价'                                            ,
		`promotion_cost_price`    decimal(26,6) COMMENT '商品促销进价'                                            ,
		`promotion_price`         decimal(26,6) COMMENT '商品促销售价'                                            ,
		`supplier_cost_rate`      decimal(26,6) COMMENT '供应商摊分比例'                                           ,
		`tax_rate`                decimal(13,6) COMMENT '税费比例'                                              ,
		`order_qty`               decimal(26,6) COMMENT '下单数量'                                              ,
		`sales_qty`               decimal(26,6) COMMENT '销售数量'                                              ,
		`sales_value`             decimal(26,6) COMMENT '含税销售额'                                             ,
		`sales_cost`              decimal(26,6) COMMENT '含税销售成本'                                            ,
		`profit`                  decimal(26,6) COMMENT '含税毛利'                                              ,
		`front_profit`            decimal(26,6) COMMENT '前端含税毛利'                                            ,
		`promotion_deduction`     decimal(26,6) COMMENT '含税促销扣款'                                            ,
		`excluding_tax_sales`     decimal(26,6) COMMENT '不含税销售额'                                            ,
		`excluding_tax_cost`      decimal(26,6) COMMENT '不含税销售成本'                                           ,
		`excluding_tax_profit`    decimal(26,6) COMMENT '不含税毛利'                                             ,
		`excluding_tax_deduction` decimal(26,6) COMMENT '不含税促销扣款'                                           ,
		`tax_value`               decimal(26,6) COMMENT '税金'                                                ,
		`sales_tax_rate`          decimal(26,6) COMMENT '销项税率'                                              ,
		`cost_tax_rate`           decimal(26,6) COMMENT '进项税率'                                              ,
		`vendor_code` string COMMENT '供应商编码(业务主键)'                                                          ,
		`vendor_name` string COMMENT '供应商名称'                                                                ,
		`run_type` string COMMENT '经营方式,0标识自营,1标识联营'                                                        ,
		`storage_location` string COMMENT '库存地点'                                                            ,
		`bill_type` string COMMENT '开票类型'                                                                   ,
		`bill_type_name` string COMMENT '开票类型名称'                                                            ,
		`return_flag` string COMMENT '退货标识'                                                                 ,
		`customer_group` string COMMENT '组'                                                               ,
		`sap_origin_dc_code` string COMMENT 'sap原始dc编码'                                                     ,
		`sap_origin_dc_name` string COMMENT 'sap原始dc名称'                                                     ,
		`order_mode` int COMMENT '订单模式：0-配送,1-直送，2-自提，3-直通'                                                 ,
		`order_kind` string COMMENT '订单类型：NORMAL-普通单，WELFARE-福利单'                                           ,
		`channel` string COMMENT '战报渠道编码'                                                                   ,
		`channel_name` string COMMENT '战报渠道名称'                                                              ,
		`province_code` string COMMENT '战报省区编码'                                                             ,
		`province_name` string COMMENT '战报省区名称'                                                             ,
		`city_name` string COMMENT '战报城市名称'                                                                 ,
		`city_real` string COMMENT '战报城市组名称'                                                                ,
		`cityjob` string COMMENT '战报城市组负责人'                                                                 ,
		`province_manager_id` string COMMENT '战报省区负责人id'                                                    ,
		`province_manager_work_no` string COMMENT '战报省区负责人工号'                                               ,
		`province_manager_name` string COMMENT '战报省区负责人名称'                                                  ,
		`workshop_code` string COMMENT '车间编码'                                                               ,
		`workshop_name` string COMMENT '车间名称'                                                               ,
		`is_factory_goods_code` int COMMENT '是否工厂商品，1是，0否'                                                  ,
		`is_factory_goods_name` string COMMENT '是否工厂商品'
	)
	PARTITIONED BY
	(
		`sdt` string,
		`sales_type` string COMMENT 'qyg标识销售W0A/99销售（企业购）、gc标识工厂端销售到门店, anhui标识新系统企业购,
  anhui_md标识新系统门店销售'
	)
	ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
	STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat' LOCATION 'hdfs://nameservice1/user/hive/warehouse/csx_dw.db/dws_sale_r_d_customer_sale' TBLPROPERTIES
	(
		'parquet.compression'  ='SNAPPY',
		'transient_lastDdlTime'='1584421328'
	)