create table csx_dw.order_flow 
(
order_date   string comment'订单日期',
order_code                                                      string comment'订单号',
super_class                                                     string comment'订单单据类型',
super_class_name      string comment'订单单据类型名称',
original_order_code       string comment'源订单号',
link_order_code           string comment'关联订单号',
shipped_order_code        string comment'出库单号',
received_order_code       string comment'入库单号',
direct_flag               string comment'是否直通',
zm_direct_flag            string comment'是否帐面直通',
customer_direct_flag      string comment'是否直送',
local_purchase_flag       string comment'是否地采',
addition_order_flag       string comment'是否加配',
order_status  string comment'订单单据状态',
system_status             string comment'系统状态',
source_type               string comment'订单来源',
source_type_name     string comment'订单来源名称',
vender_code              string comment'供应商号',
vender_name              string comment'供应商名称',
org_vender_code              string comment'原供应商号',
send_location_code     string comment'发货地点',
send_location_name     string comment'发货名称',
receive_location_code  string comment'收货地点编码',
receive_location_name  string comment'收货地点名称',
settle_location_code   string comment'结算地点编码',
settle_location_name   string comment'结算地点名称',
purchase_org_code      string comment'采购组织',
purchase_org_name      string comment'采购组织名称',
is_compensation          string comment'是否申偿',
last_delivery_date       string comment'最迟送货日期',
order_update_time            string comment'订单更新日期',
goods_code                 string comment'商品编码',
goods_name                 string comment'商品名称',
bar_code                     string comment'商品条码',
spec                         string comment'规格',
pack_qty                     string comment'件装数',
unit                         string comment'单位',
order_qty                    decimal(26,4) comment'订单数量',
fixed_price_type             string comment'定价类型(1-移动平均价、2-系统调拨协议价、3-系统进价、4-批次价、5-手工价)',
tax_code                     string comment'税码',
tax_rate                     decimal(26,4) comment'税率',
tax_rate2                    string comment'税码2',
tax_code2                    decimal(26,4) comment'税率2',
system_price                 decimal(26,4) comment'系统进价',
manual_price                 decimal(26,4) comment'手工价',
system_transfer_price        decimal(26,4) comment'系统调拨协议价、3-系统进价、4-批次价、5-手工价',
manual_transfer_price        decimal(26,4) comment'手工调拨价',
batch_price                  decimal(26,4) comment'批次价',
price1_include_tax           decimal(26,4) comment'单价1（含税）',
price1_free_tax              decimal(26,4) comment'单价1(未税)',
price2_include_tax           decimal(26,4) comment'单价2(含税)',
price2_free_tax              decimal(26,4) comment'单价2(未税)',
amount1_include_tax          decimal(26,4) comment'金额1(含税)',
amount1_free_tax             decimal(26,4) comment'金额1(未税)',
amount2_include_tax          decimal(26,4) comment'金额2(含税)',
amount2_free_tax             decimal(26,4) comment'金额2(未税)',
order_amount                 decimal(26,4) comment'订单额(含税)',
order_un_amount              decimal(26,4) comment'订单额(未税)',
price_markup_proportion      decimal(26,4) comment'加价比例',
dept_code                      string comment'课组编码',
dept_name                    string comment'课组名称',
category_code              string comment'部类编码',
category_name              string comment'部类名称',
category_large_code          string comment'大类编码',
category_large_name          string comment'大类名称',
category_small_code          string comment'小类编码',
category_small_name          string comment'小类名称',
receive_batch_code           string comment'入库批次号',
direct_price                 decimal(26,4) comment'帐面直通进价',
direct_amount                decimal(26,4) comment'帐面直通金额',
return_flag                  string comment'退货标识',
receive_super_class          string comment'收货类型( 1-正常收货 2-无单收货 3-异常收货地点)',
receive_store_location_code  string comment'收货库存编码',
receive_store_location_name  string comment'收货库存名称',
shelf_store_location_type    string comment'上架至（上架储位类型）',
shelf_area_code              string comment'收货储位编码',
shelf_area_name              string comment'收货储位名称',
shelf_store_location_code    string comment'上架储位编码',
shelf_store_location_name    string comment'上架储位',
receive_status               string comment'收货状态 0-待收货 1-收货中 2-已关单 3-已取消',
shelf_status                 string comment'上架状态 0-待上架 1-上架中 2-已上架',
all_receive_flag             string comment'全量收货',
all_shelf_flag               string comment'全量上架',
receive_compensation_type  string comment'1寄售申偿，2.云超销售申偿，3.自营小店申偿，4.调拨申偿',
business_type              string comment'业务类型',
entry_type                   string comment'订单类型（P01、T06）',
assess_type                string comment'评估类型',
assess_type_name           string comment'评估类型名称',
source_system              string comment'来源系统',
receive_qty                decimal(26,4) comment'收货数量',
shelf_qty                  decimal(26,4) comment'上架数量',
receive_pass_qty           decimal(26,4) comment'申偿通过数量',
receive_reject_qty         decimal(26,4) comment'申偿拒绝数量',
receive_price              decimal(26,4) comment'入库进价',
recevie_add_price_percent  decimal(26,4) comment'入库加价比例',
receive_amount             decimal(26,4) comment'入库金额',
receive_date               string comment'收货时间',
receive_close_time         string comment'关单时间',
shipped_batch_code  string comment'出库批次号',
shipped_qty                decimal(26,4) comment'出库数量',
picking_side_qty           decimal(26,4) comment'拣选面出库数',
store_location_qty         decimal(26,4) comment'储位出库数',
shipped_price              decimal(26,4) comment'出库单价',
shipped_add_price_percent  decimal(26,4) comment'加价比例',
shipped_amount             decimal(26,4) comment'出库金额',
shipped_area_code            string comment'出库库区',
shipped_area_name            string comment'出库库区名称',
shipped_store_location_code  string comment'出库储位编码',
shipped_store_location_name  string comment'出库储位名称',
all_send_flag                string comment'全量发货',
running_model                string comment'运转模式',
picking_type                 string comment'拣货类型 1-移动端拣货 2-电子称拣货',
tc_picking_flag              string comment'TC商品是否拣货 0-否 1-是',
price_type                   string comment'价格类型 1-成本 2-协议价 3-系统进价',
shipped_source_system        string comment'来源系统',
shipped_super_class          string comment'出库单据类型',
shipped_type                 string comment'订单类型',
shipped_business_type        string comment'业务类型',
shipped_return_flag          string comment'退货标识',
transfer_location_code       string comment'转配地点编码',
transfer_location_name       string comment'转配地点',
shipped_status  string comment'出库单状态',
all_received_flag  string comment'全量收货',
shipped_finish_time  string comment'出库完成时间'
)comment '订单流表'
partitioned by 
(
  order_sdt string COMMENT '订单日期分区',
  receive_sdt string comment'入库分区',
  shipped_sdt string comment'出库分区'
)
row format delimited stored as Parquet