DROP table csx_dw.wms_shipped_order;
CREATE TABLE `csx_dw.wms_shipped_order`(
  `id` string COMMENT '主键', 
  `batch_id` bigint COMMENT '批次明细id', 
  `order_id` bigint COMMENT '订单明细id', 
  `header_id` bigint COMMENT '订单头id', 
  `batch_code` string COMMENT '出库批次号', 
  `order_no` string COMMENT '出库单号 规则OU+年（2位）+月（2位）+日（2位）+6位流水', 
  `link_scm_order_no` string COMMENT '关联采购单号', 
  `split_order_no` string COMMENT '拆单单号', 
  `goods_code` string COMMENT '商品编号', 
  `goods_bar_code` string COMMENT '商品条码', 
  `goods_name` string COMMENT '商品名称', 
  `division_code` string comment '部类',
  division_name string comment '部类名称 ',
  department_id  string comment '课组名称 ',
  department_name  string comment '课组名称 ',
  category_large_code string comment '大类编码',
  category_large_name string comment '大类名称',
  category_middle_code string comment '中类编码',
  category_middle_name string comment '中类名称',
  category_small_code string comment '小类编码',
  `category_small_name` string comment '小类名称',
  `unit` string COMMENT '单位', 
  `sale_unit` string COMMENT '销售单位', 
  `split_group_code` string COMMENT '拆单分组编号', 
  `split_group_name` string COMMENT '拆单分组名称', 
  `plan_qty` decimal(10,2) COMMENT '计划数量', 
  `order_shipped_qty` decimal(10,2) COMMENT '订单出库数量', 
  `shipped_qty` decimal(10,2) COMMENT '批次出库数量', 
  `picking_side_qty` decimal(10,2) COMMENT '拣选面出库数', 
  `store_location_qty` decimal(10,2) COMMENT '储位出库数', 
  `receive_qty` decimal(10,2) COMMENT '对方收货数量', 
  `pass_qty` decimal(10,2) COMMENT '通过申偿量', 
  `reject_qty` decimal(10,2) COMMENT '拒绝申偿量', 
  `price` decimal(10,2) COMMENT '价格', 
  `add_price_percent` decimal(10,2) COMMENT '加价比例', 
  `amount` decimal(12,4) COMMENT '金额', 
  `direct_price` decimal(10,2) COMMENT '账面直通单价', 
  `direct_amount` decimal(12,4) COMMENT '账面直通总价', 
  `shipped_location_code` string COMMENT '出库地点编码', 
  `shipped_location_name` string COMMENT '出库地点名称', 
  `shipped_area_code` string COMMENT '出库库区编码', 
  `shipped_area_name` string COMMENT '出库库区名称', 
  `shipped_store_location_code` string COMMENT '出库储位编码', 
  `shipped_store_location_name` string COMMENT '出库储位名称', 
  `all_send_flag` int COMMENT '全量发货 0-否 1-是', 
  `running_model` string COMMENT '运转模式 DC/TC', 
  `picking_type` int COMMENT '拣货类型 1-移动端拣货 2-电子称拣货', 
  `tc_picking_flag` int COMMENT 'TC商品是否拣货 0-否 1-是', 
  `remark` string COMMENT '备注', 
  `specs_remark` string COMMENT '规格备注', 
  `handle_remark` string COMMENT '加工备注', 
  `run_type` int COMMENT '经营方式 1-联营 2-自营', 
  `assess_type` string COMMENT '评估类', 
  `assess_type_name` string COMMENT '评估类名称', 
  `tax_type` int COMMENT '税类型 1-进项税 2-销项税', 
  `tax_rate` decimal(10,2) COMMENT '进项税率', 
  `tax_code` string COMMENT '进项税码', 
  `price_type` int COMMENT '价格类型 1-成本 2-协议价 3-系统进价', 
  `source_system` string COMMENT '来源系统', 
  `super_class` int COMMENT '类型 1-正常出库单 2-异常出库单', 
  `shipped_type_code` string COMMENT '订单类型', 
   shipped_type string comment '订单类型名称',
  `business_type_code` string COMMENT '业务类型', 
  `business_type` string COMMENT '业务类型名称', 
  `return_flag` string COMMENT '退货标识', 
  `direct_flag` string COMMENT '账面直通标识', 
  `shipper_code` string COMMENT '货主编号', 
  `shipper_name` string COMMENT '货主名称', 
  `supplier_code` string COMMENT '收货供应商编码', 
  `supplier_name` string COMMENT '收货供应商名称', 
  `receive_location_code` string COMMENT '收货地点编码', 
  `receive_location_name` string COMMENT '收货地点名称', 
  `transfer_location_code` string COMMENT '转配地点编码', 
  `transfer_location_name` string COMMENT '转配地点名称', 
  `customer_code` string COMMENT '编号', 
  `customer_name` string COMMENT '名称', 
  `sub_customer_code` string COMMENT '子客戶号', 
  `sub_customer_address` string COMMENT '子地址', 
  `shop_type` string COMMENT '门店类型', 
  `shop_code` string COMMENT '门店编号', 
  `shop_name` string COMMENT '门店名称', 
  `shop_address` string COMMENT '门店地址', 
  `station_code` string COMMENT '站点编号', 
  `station_name` string COMMENT '站点名称', 
  `receive_name` string COMMENT '收货人姓名', 
  `receive_phone_number` string COMMENT '收货人电话', 
  `receive_province_code` string COMMENT '收货人省份编码', 
  `receive_province_name` string COMMENT '收货人省份名称', 
  `receive_city_code` string COMMENT '收货人市编码', 
  `receive_city_name` string COMMENT '收货人市名称', 
  `receive_area_code` string COMMENT '收货人区县编码', 
  `receive_area_name` string COMMENT '收货人区县名称', 
  `receive_address` string COMMENT '收货地址', 
  `delivery_code` string COMMENT '配送方编号', 
  `delivery_name` string COMMENT '配送方名称', 
  `settlement_dc` string COMMENT '结算DC', 
  `settlement_dc_name` string COMMENT '结算DC名称', 
  `status` int COMMENT '状态 0-初始 1-已集波 2-分配中 3-已分配 4-拣货中 5-拣货完成 6-已发货 7-已完成', 
  `wave_code` string COMMENT '波次号', 
  `distribute_shortage_flag` int COMMENT '分配短缺 0-否 1-是', 
  `all_received_flag` int COMMENT '全量收货 0-否 1-是', 
  `print_times` int COMMENT '出库单打印次数', 
  `packages_number` int COMMENT '包裹单数', 
  `link_operate_order_no` string COMMENT '关联操作订单', 
  `origin_order_no` string COMMENT '来源单号', 
  `link_in_out_order_no` string COMMENT '关联出入库单号', 
  `link_order_no` string COMMENT '关联单号', 
  `external_order_no` string COMMENT '外部单号', 
  `send_time` string COMMENT '发货时间', 
  `auto_status` int COMMENT '是否自动执行 0-否 1-是', 
  `sale_channel` int COMMENT '销售渠道 1-云超 2-云创 3-寄售 4-自营小店 5.BBC,6.红旗,7.B端', 
  `compensation_type` int COMMENT '申偿类型 1.寄售申偿，2.云超销售申偿，3.自营小店申偿，4.调拨申偿', 
  `plan_date` string COMMENT '计划出库日期', 
  `order_type` int COMMENT '订单类型 1-普通单 2-福利单', 
  `finish_time` string COMMENT '订单完成时间', 
  `create_time` string COMMENT '创建时间', 
  `create_by` string COMMENT '创建者', 
  `update_time` string COMMENT '更新时间', 
  `update_by` string COMMENT '更新者')comment'发货出库宽表'
PARTITIONED BY ( 
  `sdt` string COMMENT '日期分区')
STORED AS parquet 
--'hdfs://nameservice1/user/hive/warehouse/csx_dw.db/wms_shipped_order'

;

select 
	a.id,
	batch_id,
	order_id,
	header_id,
	batch_code,
	order_no,
	link_scm_order_no,
	split_order_no,
	goods_code,
	goods_bar_code,
	goods_name,
	unit,
	b.division_code,
	b.division_name,
	b.department_id,
	b.department_name,
	b.category_large_code,
	b.category_large_name,
	b.category_middle_code,
	category_middle_name,
	category_small_code,
	category_small_name,
	sale_unit,
	split_group_code,
	split_group_name,
	plan_qty,
	order_shipped_qty,
	shipped_qty,
	picking_side_qty,
	store_location_qty,
	receive_qty,
	pass_qty,
	reject_qty,
	price,
	add_price_percent,
	amount,
	direct_price,
	direct_amount,
	shipped_location_code,
	shipped_location_name,
	shipped_area_code,
	shipped_area_name,
	shipped_store_location_code,
	shipped_store_location_name,
	all_send_flag,
	running_model,
	picking_type,
	tc_picking_flag,
	remark,
	specs_remark,
	handle_remark,
	run_type,
	assess_type,
	assess_type_name,
	tax_type,
	tax_rate,
	tax_code,
	price_type,
	source_system,
	super_class,
	a.shipped_type_code,
	c.wms_order_type,
	a.business_type_code,
	c.business_type,
	return_flag,
	direct_flag,
	shipper_code,
	shipper_name,
	supplier_code,
	supplier_name,
	receive_location_code,
	receive_location_name,
	transfer_location_code,
	transfer_location_name,
	customer_code,
	customer_name,
	sub_customer_code,
	sub_customer_address,
	shop_type,
	shop_code,
	shop_name,
	shop_address,
	station_code,
	station_name,
	receive_name,
	receive_phone_number,
	receive_province_code,
	receive_province_name,
	receive_city_code,
	receive_city_name,
	receive_area_code,
	receive_area_name,
	receive_address,
	delivery_code,
	delivery_name,
	settlement_dc,
	settlement_dc_name,
	status,
	wave_code,
	distribute_shortage_flag,
	all_received_flag,
	print_times,
	packages_number,
	link_operate_order_no,
	origin_order_no,
	link_in_out_order_no,
	link_order_no,
	external_order_no,
	send_time,
	auto_status,
	sale_channel,
	compensation_type,
	plan_date,
	order_type,
	finish_time,
	a.create_time,
	a.create_by,
	a.update_time,
	a.update_by,
	a.sdt
from
(select
	id,
	batch_id,
	order_id,
	header_id,
	batch_code,
	order_no,
	link_scm_order_no,
	split_order_no,
	goods_code,
	goods_bar_code,
	goods_name,
	unit,
	sale_unit,
	split_group_code,
	split_group_name,
	plan_qty,
	order_shipped_qty,
	shipped_qty,
	picking_side_qty,
	store_location_qty,
	receive_qty,
	pass_qty,
	reject_qty,
	price,
	add_price_percent,
	amount,
	direct_price,
	direct_amount,
	shipped_location_code,
	shipped_location_name,
	shipped_area_code,
	shipped_area_name,
	shipped_store_location_code,
	shipped_store_location_name,
	all_send_flag,
	running_model,
	picking_type,
	tc_picking_flag,
	remark,
	specs_remark,
	handle_remark,
	run_type,
	assess_type,
	assess_type_name,
	tax_type,
	tax_rate,
	tax_code,
	price_type,
	source_system,
	super_class,
	shipped_type as shipped_type_code,
	business_type as business_type_code,
	return_flag,
	direct_flag,
	shipper_code,
	shipper_name,
	supplier_code,
	supplier_name,
	receive_location_code,
	receive_location_name,
	transfer_location_code,
	transfer_location_name,
	customer_code,
	customer_name,
	sub_customer_code,
	sub_customer_address,
	shop_type,
	shop_code,
	shop_name,
	shop_address,
	station_code,
	station_name,
	receive_name,
	receive_phone_number,
	receive_province_code,
	receive_province_name,
	receive_city_code,
	receive_city_name,
	receive_area_code,
	receive_area_name,
	receive_address,
	delivery_code,
	delivery_name,
	settlement_dc,
	settlement_dc_name,
	status,
	wave_code,
	distribute_shortage_flag,
	all_received_flag,
	print_times,
	packages_number,
	link_operate_order_no,
	origin_order_no,
	link_in_out_order_no,
	link_order_no,
	external_order_no,
	send_time,
	auto_status,
	sale_channel,
	compensation_type,
	plan_date,
	order_type,
	finish_time,
	create_time,
	create_by,
	update_time,
	update_by,
	sdt
from
	csx_dw.wms_shipped_order_m
where 1=1 and sdt='20200317')a
left join 
(SELECT goods_id,
       division_code,
       division_name,
       category_large_code,
       category_large_name,
       category_middle_code,
       category_middle_name,
       category_small_code,
       category_small_name,
       department_id,
       department_name
FROM csx_dw.goods_m
WHERE sdt='20200317') b on a.goods_code=b.goods_id 
left join 
(
	select
		*
	from
		csx_ods.source_wms_r_d_bills_config
	where
		sdt = regexp_replace(to_date(date_sub(CURRENT_TIMESTAMP(),
		1)),
		'-',
		'')
 ) c  on a.business_type_code= c.business_type_code and a.shipped_type_code=c.type_code