CREATE TABLE `csx_tmp.report_wms_r_d_turnover_fresh_fr`(
  `zone_id` string comment '大区编码', 
  `zone_name` string comment '大区名称', 
  `dist_code` string comment '省区编码', 
  `dist_name` string comment '省区名称', 
  `city_code` string comment '城市编码', 
  `city_name` string comment '城市名称', 
  `dc_code` string comment 'DC编码',
  `dc_name` string comment 'dc名称', 
  `classify_large_code` string comment '管理一级分类', 
  `classify_large_name` string comment '管理一级分类名称', 
  `classify_middle_code` string comment '管理二级分类', 
  `classify_middle_name` string comment '管理二级分类', 
  `classify_small_code` string comment'管理三级分类', 
  `classify_small_name` string comment'管理三级分类', 
  `final_qty` decimal(38,6) comment '期末库存量', 
  `final_amt` decimal(38,6) comment '期末库存额', 
  `period_inv_amt_30day` decimal(38,6) comment '期间30天库存成本', 
  `cost_sum` decimal(38,6) comment '期间30天成本：销售成本+领用+原料消耗', 
  `turnover_days` decimal(38,6)comment '30天周转天数', 
  `receipt_amt` decimal(38,6) comment '近30天领用成本', 
  `receipt_qty` decimal(38,6) comment '近30天领用数量', 
  `material_take_amt` decimal(38,6)comment '近30天原料消耗额',
  `material_take_qty` decimal(38,6)comment '近30天原料消耗量', 
  `cost_30day` decimal(38,6) comment '近30天销售成本', 
  `stock_sku` bigint comment '库存SKU数', 
  `final_amt_7` decimal(38,6) comment '0-7天库存金额', 
  `final_amt_15` decimal(38,6) comment '7-15库存金额', 
  `final_amt_40` decimal(38,6) comment '15-40天库存金额', 
  `final_amt_365` decimal(38,6) comment '40-365库存金额', 
  `final_amt_365_last` decimal(38,6) comment '365天以库存金额', 
  `stock_sku_7` bigint comment '0-7天SKU', 
  `stock_sku_15` bigint comment '7-15天SKU', 
  `stock_sku_40` bigint comment '15-40天SKU', 
  `stock_sku_365` bigint comment '40-365天SKU', 
  `stock_sku_365_last` bigint comment '365天以上SKU'
  `stock_sku_ratio_7` bigint comment '0-7天SKU占比', 
  `stock_sku_ratio_15` bigint comment '7-15天SKU占比', 
  `stock_sku_ratio_40` bigint comment '15-40天SKU占比', 
  `stock_sku_ratio_365` bigint comment '40-365天SKU占比', 
  `stock_sku_ratio_365_last` bigint comment '365天以上SKU占比',
  `final_amt_ratio_7` decimal(38,6) comment '0-7天库存金额占比', 
  `final_amt_ratio_15` decimal(38,6) comment '7-15库存金额占比', 
  `final_amt_ratio_40` decimal(38,6) comment '15-40天库存金额占比', 
  `final_amt_ratio_365` decimal(38,6) comment '40-365库存金额占比', 
  `final_amt_ratio_365_last` decimal(38,6) comment '365天以库存金额占比',
  updatetime stamptime comment '更新日期'
  )comment '生鲜库存周转占比'
 partitioned by (sdt string comment '数据分区日期')
STORED AS quaret 
