select 
a.order_code                   ,
source_order_code            ,
super_class                  ,
original_order_code          ,
a.link_order_code              ,
source_location_code         ,
source_location_name         ,
target_location_code         ,
target_location_name         ,
settle_location_code         ,
settle_location_name         ,
supplier_code                ,
supplier_name                ,
a.goods_code                   ,
goods_name                   ,
bar_code                     ,
spec                         ,
pack_qty                     ,
unit                         ,
order_qty                    ,
category_code                ,
category_name                ,
category_large_code          ,
category_large_name          ,
category_middle_code         ,
category_middle_name         ,
category_small_code          ,
category_small_name          ,
status                         ,
source_type                    ,
source_type_name               ,
supplier_code                  ,
supplier_name                  ,
purchase_org_code              ,
purchase_org_name              ,
purchase_group_code            ,
purchase_group_name            ,
direct_flag                    ,
zm_direct_flag                 ,
customer_direct_flag           ,
local_purchase_flag            ,
is_compensation                ,
addition_order_flag            ,
system_status                  ,
last_delivery_date             ,
return_reason_code             ,
return_reason_name             ,
create_by                      ,
create_time                    ,
update_time                    ,
fixed_price_type               ,
tax_code                       ,
tax_rate                       ,
price_include_tax              ,
order_trace_qty                ,
order_trace_amount_include_tax ,
-- 以下入库数据
b.receipt_no                   ,
b.receip_batch_code                    ,
produce_date                   ,
receive_qty                    ,
b.entry_price                         ,
b.entry_amt                        ,
b.return_flag                    ,
receive_super_class                    ,
sale_channel                   ,
compensation_type              ,
run_type                       ,
entry_type_code                ,
entry_type                     ,
b.entry_business_type_code             ,
b.entry_business_type                  ,
b.receive_time,
-- 以下出库数据
shipped_no                       ,
c.shipped_batch_code,
c.shipped_price                          ,
c.shipped_amt                       ,
shipped_qty                    ,
c.shipped_super_class                    ,
shipped_type_code              ,
shipped_type                   ,
shipped_business_type_code            ,
c.shipped_business_type                 ,
send_time
from csx_dw.dws_scm_r_d_scm_order_info a 

left join 
(select order_code as receipt_no,batch_code as receip_batch_code,link_operate_order_code,goods_code,produce_date,receive_qty,price as entry_price,amount as entry_amt,super_class as receive_super_class,sale_channel,compensation_type,run_type,entry_type_code,entry_type,business_type_code as entry_business_type_code,
    business_type as entry_business_type,receive_time,return_flag from csx_dw.wms_entry_order where sdt>='20200501') b on a.order_code=b.link_operate_order_code and a.goods_code=b.goods_code
left join 
(select order_no as shipped_no,batch_code as shipped_batch_code,link_order_no,goods_code,shipped_qty,price as shipped_price,amount as shipped_amt,super_class as shipped_super_class,shipped_type_code,shipped_type,
business_type_code as shipped_business_type_code,
business_type as shipped_business_type,send_time from csx_dw.wms_shipped_order  where sdt>='20200501') c on a.order_code=c.link_order_no and a.goods_code=c.goods_code
where a.sdt>='20200501'
