-- 财务采购整体分析
set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;
set hive.support.quoted.identifiers=none;
set hive.exec.max.dynamic.partitions=20000;
set hive.exec.max.dynamic.partitions.pernode =20000;

-- 大区处理
-- 大区处理 增加低毛利DC 标识,关联供应链仓信息
drop table csx_analyse_tmp.csx_analyse_tmp_group_dc_new ;
create  TABLE csx_analyse_tmp.csx_analyse_tmp_group_dc_new as 
select case when performance_region_code!='10' then '大区'else '平台' end dept_name,
    purchase_org,
    purchase_org_name,
    belong_region_code  region_code,
    belong_region_name  region_name,
    shop_code ,
    shop_name ,
    company_code ,
    company_name ,
    purpose,
    purpose_name,
    basic_performance_city_code as performance_city_code,
    basic_performance_city_name as performance_city_name,
    basic_performance_province_code as performance_province_code,
    basic_performance_province_name as performance_province_name,
    case when c.dc_code is not null then '1' else '0' end as is_purchase_dc ,
    enable_date,
    shop_low_profit_flag
from csx_dim.csx_dim_shop a 
 left join 
 (select belong_region_code,
        belong_region_name,
        performance_province_code,
        performance_province_name,
        performance_city_code,
        performance_city_name
  from csx_dim.csx_dim_basic_performance_attribution) b on a.basic_performance_city_code= b.performance_city_code
 left join 
 (select dc_code,regexp_replace(to_date(enable_time),'-','') enable_date 
 from csx_dim.csx_dim_csx_data_market_conf_supplychain_location 
 where sdt='current') c on a.shop_code=c.dc_code
 where sdt='current'    
    ;
    
    

 drop table  csx_analyse_tmp.csx_analyse_tmp_group_purchase_01 ;
create  table csx_analyse_tmp.csx_analyse_tmp_group_purchase_01 as 
SELECT dept_name,
       d.region_code,
       d.region_name,
       d.performance_province_code province_code,
       d.performance_province_name province_name,
       d.performance_city_code city_code,
       d.performance_city_name city_name,
       a.order_business_type,
       a.supplier_classify_code,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       supplier_code,
       d.is_purchase_dc,
       case when a.supplier_name like '%永辉%' then '云超配送'
            when business_type_name like '云超配送%' then '云超配送'
       else '供应商配送' end business_type_name,
       case when a.division_code in ('10','11') then '11' else '12' end bd_id,
       case when a.division_code in ('10','11') then '生鲜' else '食百' end bd_name,
       sum(receive_amt) as receive_amt,
       sum(no_tax_receive_amt) as no_tax_receive_amt,
       sum(shipped_amt) as shipped_amt,
       sum(no_tax_shipped_amt) as no_tax_shipped_amt,
       sum(coalesce(receive_amt,0)-coalesce(shipped_amt,0)) AS net_entry_amount,
       sum(no_tax_receive_amt-no_tax_shipped_amt) as not_tax_net_entry_amount,
       coalesce(sum(case when d.is_purchase_dc='1' and classify_large_code ='B02' 
                     then coalesce(receive_amt,0)-coalesce(shipped_amt,0) end ),0) as B02_entry_amount,
       coalesce(sum(case when order_business_type=1 and classify_large_code ='B02' and d.is_purchase_dc='1' 
                     then coalesce(receive_amt,0)-coalesce(shipped_amt,0) end ),0 ) base_entry_amount,
       coalesce(sum(case when d.is_purchase_dc='1' and classify_large_code ='B02' 
                     then coalesce(no_tax_receive_amt,0)-coalesce(no_tax_shipped_amt,0) end ),0) as B02_no_tax_entry_amount,
       coalesce(sum(case when order_business_type=1 and classify_large_code ='B02' and d.is_purchase_dc='1' 
                     then coalesce(no_tax_receive_amt,0)-coalesce(no_tax_shipped_amt,0) end ),0 ) base_no_tax_entry_amount,
       d.purpose,
       sdt,
       substr(sdt,1,6) months,
       concat(substr(sdt,1,4),'Q',floor(substr(sdt,5,2)/3.1)+1) quarter  ,
       substr(sdt,1,4) year,
       t.week_of_year,
       concat(t.week_begin,'-',week_end) as week_date,
       enable_date
FROM csx_analyse.csx_analyse_scm_purchase_order_flow_di a 
left join csx_analyse_tmp.csx_analyse_tmp_group_dc_new d on a.dc_code=d.shop_code 
left join csx_dim.csx_dim_basic_date t on a.sdt=t.calday
WHERE  receive_sdt <= '20220930'
   and receive_sdt>= '20220901'
   and sdt>='20220101'
  and source_type_code not in ('4','15','18') -- 剔除 4项目合伙人、15联营直送、18城市服务商
  and super_class_code in (1,2)    -- 1供应商订单、2供应商退货单
  -- and is_purchase_dc=1
  and d.purpose in ('01','02','03','05','07','08')
  GROUP BY dept_name,
       d.region_code,
       d.region_name,
       d.performance_city_code,
       d.performance_city_name,
       d.performance_province_code,
       d.performance_province_name,
       a.order_business_type,
       a.supplier_classify_code,
       classify_middle_name,
       a.classify_middle_code,
       supplier_code,
       case when a.supplier_name like '%永辉%' then '云超配送'
       when business_type_name like '云超配送%' then '云超配送'
              ELSE '供应商配送' end ,
       case when a.division_code in ('10','11') then '11' else '12' end ,
       case when a.division_code in ('10','11') then '生鲜' else '食百' end,
       classify_large_code,
       classify_large_name,
       sdt,
       d.is_purchase_dc,
       d.purpose,
       enable_date,
        substr(sdt,1,6) ,
       concat(substr(sdt,1,4),'Q',floor(substr(sdt,5,2)/3.1)+1)   ,
       substr(sdt,1,4),
       t.week_of_year,
       concat(t.week_begin,'-',week_end) 
;


-- select * from csx_analyse_tmp.csx_analyse_tmp_group_purchase_01;

-- 周入库情况
drop table csx_analyse_tmp.csx_analyse_tmp_group_purchase_w;
create  table csx_analyse_tmp.csx_analyse_tmp_group_purchase_w as
SELECT dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       sum(receive_amt) as receive_amt,
       sum(no_tax_receive_amt) as no_tax_receive_amt,
       sum(shipped_amt ) as shipped_amt,
       sum(no_tax_shipped_amt) as no_tax_shipped_amt,
       sum( net_entry_amount) net_entry_amount,
       sum( not_tax_net_entry_amount) no_tax_net_entry_amount,
       sum(coalesce(case when supplier_classify_code=2 then net_entry_amount end  ,0  ) ) cash_entry_amount,  -- 现金采购
       sum(coalesce(case when supplier_classify_code=2 then not_tax_net_entry_amount end  ,0  ) ) cash_no_tax_entry_amount,  -- 未税现金采购
       sum(coalesce(case when business_type_name='云超配送' then net_entry_amount end,0) ) yh_entry_amount,    -- 云超采购
       sum(coalesce(case when business_type_name='云超配送' then not_tax_net_entry_amount end,0) ) yh_no_tax_entry_amount,    -- 云超采购
       count( distinct supplier_code ) as all_num,
       count( distinct case when supplier_classify_code=2 then supplier_code end   )    as cash_entry_num,
       count( distinct case when business_type_name='云超配送' then supplier_code end ) as yh_entry_num,
       week_of_year
FROM
    csx_analyse_tmp.csx_analyse_tmp_group_purchase_01  a    
GROUP BY dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       week_of_year
GROUPING SETS
    ( (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       week_of_year),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       week_of_year),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       bd_id,
       bd_name,
       week_of_year),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       week_of_year),
       (dept_name,
       region_code,
       region_name,
       week_of_year),
       (dept_name,
       region_code,
       region_name,
       bd_id,
       bd_name,
       week_of_year),
       (dept_name,
       week_of_year),
       (dept_name,
       bd_id,
       bd_name,
       week_of_year),
        (
       bd_id,
       bd_name,
      week_of_year),
       (week_of_year))
       ;


-- 月度整体入库
drop table csx_analyse_tmp.csx_analyse_tmp_group_purchase_m;
create  table csx_analyse_tmp.csx_analyse_tmp_group_purchase_m as
SELECT dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       sum(receive_amt) as receive_amt,
       sum(no_tax_receive_amt) as no_tax_receive_amt,
       sum(shipped_amt ) as shipped_amt,
       sum(no_tax_shipped_amt) as no_tax_shipped_amt,
       sum( net_entry_amount) net_entry_amount,
       sum( not_tax_net_entry_amount) no_tax_net_entry_amount,
       sum(coalesce(case when supplier_classify_code=2 then net_entry_amount end  ,0  ) ) cash_entry_amount,  -- 现金采购
       sum(coalesce(case when supplier_classify_code=2 then not_tax_net_entry_amount end  ,0  ) ) cash_no_tax_entry_amount,  -- 未税现金采购
       sum(coalesce(case when business_type_name='云超配送' then net_entry_amount end,0) ) yh_entry_amount,    -- 云超采购
       sum(coalesce(case when business_type_name='云超配送' then not_tax_net_entry_amount end,0) ) yh_no_tax_entry_amount,    -- 云超采购
       count( distinct supplier_code ) as all_num,
       count( distinct case when supplier_classify_code=2 then supplier_code end   )    as cash_entry_num,
       count( distinct case when business_type_name='云超配送' then supplier_code end ) as yh_entry_num,
       months
FROM
    csx_analyse_tmp.csx_analyse_tmp_group_purchase_01
GROUP BY dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       months
GROUPING SETS
    ( (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       months),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       months),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       bd_id,
       bd_name,
       months),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       months),
       (dept_name,
       region_code,
       region_name,
       months),
       (dept_name,
       region_code,
       region_name,
       bd_id,
       bd_name,
       months),
       (dept_name,
       months),
       (dept_name,
       bd_id,
       bd_name,
       months),
        (
       bd_id,
       bd_name,
      months),
       (months))
       ;



-- 季度整体入库
drop table csx_analyse_tmp.csx_analyse_tmp_group_purchase_q;
create  table csx_analyse_tmp.csx_analyse_tmp_group_purchase_q as
SELECT dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       sum(receive_amt) as receive_amt,
       sum(no_tax_receive_amt) as no_tax_receive_amt,
       sum(shipped_amt ) as shipped_amt,
       sum(no_tax_shipped_amt) as no_tax_shipped_amt,
       sum( net_entry_amount) net_entry_amount,
       sum( not_tax_net_entry_amount) no_tax_net_entry_amount,
       sum(coalesce(case when supplier_classify_code=2 then net_entry_amount end  ,0  ) ) cash_entry_amount,  -- 现金采购
       sum(coalesce(case when supplier_classify_code=2 then not_tax_net_entry_amount end  ,0  ) ) cash_no_tax_entry_amount,  -- 未税现金采购
       sum(coalesce(case when business_type_name='云超配送' then net_entry_amount end,0) ) yh_entry_amount,    -- 云超采购
       sum(coalesce(case when business_type_name='云超配送' then not_tax_net_entry_amount end,0) ) yh_no_tax_entry_amount,    -- 云超采购
       count( distinct supplier_code ) as all_num,
       count( distinct case when supplier_classify_code=2 then supplier_code end   )    as cash_entry_num,
       count( distinct case when business_type_name='云超配送' then supplier_code end ) as yh_entry_num,
       quarter
FROM
    csx_analyse_tmp.csx_analyse_tmp_group_purchase_01
GROUP BY dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       quarter
GROUPING SETS
    ( (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       quarter),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       quarter),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       bd_id,
       bd_name,
       quarter),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       quarter),
       (dept_name,
       region_code,
       region_name,
       quarter),
       (dept_name,
       region_code,
       region_name,
       bd_id,
       bd_name,
       quarter),
       (dept_name,
       quarter),
       (dept_name,
       bd_id,
       bd_name,
       quarter),
        (
       bd_id,
       bd_name,
      quarter),
       (quarter))
       ;
       
--  年度汇总   
drop table csx_analyse_tmp.csx_analyse_tmp_group_purchase_y;
create  table csx_analyse_tmp.csx_analyse_tmp_group_purchase_y as
SELECT dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       sum(receive_amt) as receive_amt,
       sum(no_tax_receive_amt) as no_tax_receive_amt,
       sum(shipped_amt ) as shipped_amt,
       sum(no_tax_shipped_amt) as no_tax_shipped_amt,
       sum( net_entry_amount) net_entry_amount,
       sum( not_tax_net_entry_amount) no_tax_net_entry_amount,
       sum(coalesce(case when supplier_classify_code=2 then net_entry_amount end  ,0  ) ) cash_entry_amount,  -- 现金采购
       sum(coalesce(case when supplier_classify_code=2 then not_tax_net_entry_amount end  ,0  ) ) cash_no_tax_entry_amount,  -- 未税现金采购
       sum(coalesce(case when business_type_name='云超配送' then net_entry_amount end,0) ) yh_entry_amount,    -- 云超采购
       sum(coalesce(case when business_type_name='云超配送' then not_tax_net_entry_amount end,0) ) yh_no_tax_entry_amount,    -- 云超采购
       count( distinct supplier_code ) as all_num,
       count( distinct case when supplier_classify_code=2 then supplier_code end   )    as cash_entry_num,
       count( distinct case when business_type_name='云超配送' then supplier_code end ) as yh_entry_num,
       year
FROM
    csx_analyse_tmp.csx_analyse_tmp_group_purchase_01
GROUP BY dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       year
GROUPING SETS
    ( (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       year),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       year),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       bd_id,
       bd_name,
       year),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       year),
       (dept_name,
       region_code,
       region_name,
       year),
       (dept_name,
       region_code,
       region_name,
       bd_id,
       bd_name,
       year),
       (dept_name,
       year),
       (dept_name,
       bd_id,
       bd_name,
       year),
        (
       bd_id,
       bd_name,
      year),
       (year))
       ; 
       
 
 -- 聚合周、月、季、年   
drop table csx_analyse_tmp.csx_analyse_tmp_group_purchase_sum;
create  table csx_analyse_tmp.csx_analyse_tmp_group_purchase_sum as       
select date_m,
       case when dept_name ='合计' then '1'
            when region_name='' then '2'
            when province_name='' then '3'
            when city_name=''   then '4'
            else '5' end level_id,
       coalesce(dept_name,'合计')dept_name,
       coalesce(region_code,'00')region_code,
       case when dept_name ='大区' and region_name='' then '大区'
            when dept_name ='平台' and region_name='' then '平台'
            else region_name end   region_name,
       coalesce(province_code,'00') province_code,
       coalesce(province_name,'')   province_name,
       coalesce(city_code,'00')  as city_code,
       coalesce(city_name,'')  as city_name,
       coalesce(bd_id,'00')  as bd_id,
       coalesce(bd_name,'')  as bd_name,
       receive_amt,
       no_tax_receive_amt,
       shipped_amt,
       no_tax_shipped_amt,
       net_entry_amount,
       no_tax_net_entry_amount,
       cash_entry_amount,  -- 现金采购
       no_tax_cash_entry_amount,
       yh_entry_amount,    -- 云超采购
       no_tax_yh_entry_amount,
       all_num,
       cash_entry_num,
       yh_entry_num,
       net_entry_amount/sum(net_entry_amount)over(partition by dept_name,region_name,province_name,city_name,bd_name,sdt,date_m)*2 as net_entry_amount_ratio,
       yh_entry_amount/sum(yh_entry_amount)over(partition by dept_name,region_name,province_name,city_name,bd_name,sdt,date_m)*2 as yh_entry_amount_ratio,
       cash_entry_amount/sum(cash_entry_amount)over(partition by dept_name,region_name,province_name,city_name,bd_name,sdt,date_m)*2 as cash_entry_amount_ratio,
       no_tax_net_entry_amount/sum(net_entry_amount)over(partition by dept_name,region_name,province_name,city_name,bd_name,sdt,date_m)*2 as    no_tax_net_entry_amount_ratio,
       no_tax_yh_entry_amount/sum(yh_entry_amount)over(partition by dept_name,region_name,province_name,city_name,bd_name,sdt,date_m)*2 as      yh_no_tax_entry_amount_ratio,
       no_tax_cash_entry_amount/sum(cash_entry_amount)over(partition by dept_name,region_name,province_name,city_name,bd_name,sdt,date_m)*2 as  cash_no_tax_entry_amount_ratio,       
       all_num/sum(all_num)over(partition by dept_name,region_name,province_name,city_name,sdt,bd_name,date_m)*2 as                 all_num_ratio,
       cash_entry_num/sum(cash_entry_num)over(partition by dept_name,region_name,province_name,city_name,bd_name,sdt,date_m)*2 as   cash_entry_num_ratio,
       yh_entry_num/sum(yh_entry_num)over(partition by dept_name,region_name,province_name,city_name,bd_name,sdt,date_m)*2 as       yh_entry_num_ratio,
       sdt 
FROM (   
select 
       'week' date_m,
       coalesce(dept_name,'合计')dept_name,
       coalesce(region_code,'00')region_code,
       coalesce(region_name,'')region_name,
       coalesce(province_code,'00') province_code,
       coalesce(province_name,'')   province_name,
       coalesce(city_code,'00')  as city_code,
       coalesce(city_name,'')  as city_name,
       coalesce(bd_id,'00')  as bd_id,
       coalesce(bd_name,'')  as bd_name,
       receive_amt,
       no_tax_receive_amt,
       shipped_amt,
       no_tax_shipped_amt,
       net_entry_amount,
       no_tax_net_entry_amount,
       cash_entry_amount,  -- 现金采购
       no_tax_cash_entry_amount,
       yh_entry_amount,    -- 云超采购
       no_tax_yh_entry_amount,
       all_num,
       cash_entry_num,
       yh_entry_num,
       week_of_year sdt
FROM csx_analyse_tmp.csx_analyse_tmp_group_purchase_w
union all 
select 
       'months' date_m,
       coalesce(dept_name,'合计')dept_name,
       coalesce(region_code,'00')region_code,
       coalesce(region_name,'')region_name,
       coalesce(province_code,'00') province_code,
       coalesce(province_name,'')   province_name,
       coalesce(city_code,'00')  as city_code,
       coalesce(city_name,'')  as city_name,
       coalesce(bd_id,'00')  as bd_id,
       coalesce(bd_name,'')  as bd_name,
       receive_amt,
       no_tax_receive_amt,
       shipped_amt,
       no_tax_shipped_amt,
       net_entry_amount,
       no_tax_net_entry_amount,
       cash_entry_amount,  -- 现金采购
       no_tax_cash_entry_amount,
       yh_entry_amount,    -- 云超采购
       no_tax_yh_entry_amount,
       all_num,
       cash_entry_num,
       yh_entry_num,
       months sdt
FROM csx_analyse_tmp.csx_analyse_tmp_group_purchase_m
union all 
select 
       'quarter' date_m,
       coalesce(dept_name,'合计')dept_name,
       coalesce(region_code,'00')region_code,
       coalesce(region_name,'')region_name,
       coalesce(province_code,'00') province_code,
       coalesce(province_name,'')   province_name,
       coalesce(city_code,'00')  as city_code,
       coalesce(city_name,'')  as city_name,
       coalesce(bd_id,'00')  as bd_id,
       coalesce(bd_name,'')  as bd_name,
       receive_amt,
       no_tax_receive_amt,
       shipped_amt,
       no_tax_shipped_amt,
       net_entry_amount,
       no_tax_net_entry_amount,
       cash_entry_amount,  -- 现金采购
       no_tax_cash_entry_amount,
       yh_entry_amount,    -- 云超采购
       no_tax_yh_entry_amount,
       all_num,
       cash_entry_num,
       yh_entry_num,
       quarter sdt
FROM csx_analyse_tmp.csx_analyse_tmp_group_purchase_q 
union all 
select 
       'year' date_m,
       coalesce(dept_name,'合计')dept_name,
       coalesce(region_code,'00')region_code,
       coalesce(region_name,'')region_name,
       coalesce(province_code,'00') province_code,
       coalesce(province_name,'')   province_name,
       coalesce(city_code,'00')  as city_code,
       coalesce(city_name,'')  as city_name,
       coalesce(bd_id,'00')  as bd_id,
       coalesce(bd_name,'')  as bd_name,
       receive_amt,
       no_tax_receive_amt,
       shipped_amt,
       no_tax_shipped_amt,
       net_entry_amount,
       no_tax_net_entry_amount,
       cash_entry_amount,  -- 现金采购
       no_tax_cash_entry_amount,
       yh_entry_amount,    -- 云超采购
       no_tax_yh_entry_amount,
       all_num,
       cash_entry_num,
       yh_entry_num,
       year sdt
FROM csx_analyse_tmp.csx_analyse_tmp_group_purchase_y
) a ;


-- 周基地采购
drop table csx_analyse_tmp.csx_analyse_tmp_group_purchase_bash_w;
create   table csx_analyse_tmp.csx_analyse_tmp_group_purchase_bash_w as
SELECT dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       count( distinct  supplier_code  ) as b02_entry_num,
       count( distinct case when order_business_type=1 then supplier_code end ) as base_entry_num,
       sum(B02_entry_amount) as B02_entry_amount,
       sum(B02_no_tax_entry_amount) as B02_no_tax_entry_amount,
       sum(if(order_business_type=1,base_entry_amount,0)) as base_entry_amount,
       sum(if(order_business_type=1,base_no_tax_entry_amount,0)) as base_no_tax_entry_amount,
       week_of_year
FROM
    csx_analyse_tmp.csx_analyse_tmp_group_purchase_01 a
    where is_purchase_dc=1
    and classify_large_code ='B02'
GROUP BY dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       week_of_year
GROUPING SETS
    ( (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
      week_of_year),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       week_of_year),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       week_of_year),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       week_of_year),
       (dept_name,
       region_code,
       region_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       week_of_year),
       (dept_name,
       region_code,
       region_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       week_of_year),
       (dept_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       week_of_year),
       (dept_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       week_of_year),
        (
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       week_of_year),
       (
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       week_of_year)
       )
       ;
       
-- 月度
drop table csx_analyse_tmp.csx_analyse_tmp_group_purchase_bash_m;
create temporary table csx_analyse_tmp.csx_analyse_tmp_group_purchase_bash_m as
SELECT dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       count( distinct  supplier_code  ) as b02_entry_num,
       count( distinct case when order_business_type=1 then supplier_code end ) as base_entry_num,
       sum(B02_entry_amount) as B02_entry_amount,
       sum(B02_no_tax_entry_amount) as B02_no_tax_entry_amount,
       sum(if(order_business_type=1,base_entry_amount,0)) as base_entry_amount,
       sum(if(order_business_type=1,base_no_tax_entry_amount,0)) as base_no_tax_entry_amount,
       months
FROM
    csx_analyse_tmp.csx_analyse_tmp_group_purchase_01 a
    where is_purchase_dc=1
    and classify_large_code ='B02'
GROUP BY dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       months
GROUPING SETS
    ( (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
      months),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       months),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       months),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       months),
       (dept_name,
       region_code,
       region_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       months),
       (dept_name,
       region_code,
       region_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       months),
       (dept_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       months),
       (dept_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       months),
        (
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       months),
       (
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       months)
       
       )
       ;

-- 季度基地数据

drop table csx_analyse_tmp.csx_analyse_tmp_group_purchase_bash_q;
create  table csx_analyse_tmp.csx_analyse_tmp_group_purchase_bash_q as
SELECT dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       count( distinct  supplier_code  ) as b02_entry_num,
       count( distinct case when order_business_type=1 then supplier_code end ) as base_entry_num,
       sum(B02_entry_amount) as B02_entry_amount,
       sum(B02_no_tax_entry_amount) as B02_no_tax_entry_amount,
       sum(if(order_business_type=1,base_entry_amount,0)) as base_entry_amount,
       sum(if(order_business_type=1,base_no_tax_entry_amount,0)) as base_no_tax_entry_amount,
       quarter
FROM
    csx_analyse_tmp.csx_analyse_tmp_group_purchase_01 a
    where is_purchase_dc=1
    and classify_large_code ='B02'
GROUP BY dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       quarter
GROUPING SETS
    ( (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
      quarter),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       quarter),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       quarter),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       quarter),
       (dept_name,
       region_code,
       region_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       quarter),
       (dept_name,
       region_code,
       region_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       quarter),
       (dept_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       quarter),
       (dept_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       quarter),
        (
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       quarter),
       (
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       quarter)
       
       )
       ;


-- 年度基地数据

drop table csx_analyse_tmp.csx_analyse_tmp_group_purchase_bash_y;
create  table csx_analyse_tmp.csx_analyse_tmp_group_purchase_bash_y as
SELECT dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       count( distinct  supplier_code  ) as b02_entry_num,
       count( distinct case when order_business_type=1 then supplier_code end ) as base_entry_num,
       sum(B02_entry_amount) as B02_entry_amount,
       sum(B02_no_tax_entry_amount) as B02_no_tax_entry_amount,
       sum(if(order_business_type=1,base_entry_amount,0)) as base_entry_amount,
       sum(if(order_business_type=1,base_no_tax_entry_amount,0)) as base_no_tax_entry_amount,
       year
FROM
    csx_analyse_tmp.csx_analyse_tmp_group_purchase_01 a
    where is_purchase_dc=1
    and classify_large_code ='B02'
GROUP BY dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       year
GROUPING SETS
    ( (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
      year),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       city_code,
       city_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       year),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       year),
       (dept_name,
       region_code,
       region_name,
       province_code,
       province_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       year),
       (dept_name,
       region_code,
       region_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       year),
       (dept_name,
       region_code,
       region_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       year),
       (dept_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       year),
       (dept_name,
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       year),
        (
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       a.classify_middle_code,
       classify_middle_name,
       year),
       (
       bd_id,
       bd_name,
       classify_large_code,
       classify_large_name,
       year)
       
       )
       ;


 
 -- 基地 聚合周、月、季、年   

drop table csx_analyse_tmp.csx_analyse_tmp_group_purchase_bash_sum;
create  table csx_analyse_tmp.csx_analyse_tmp_group_purchase_bash_sum as
SELECT  date_m,
    case when dept_name ='合计' then '1'
            when region_name='' then '2'
            when province_name='' then '3'
            when city_name=''   then '4'
            else '5' end level_id,
       coalesce(dept_name,'合计')dept_name,
       coalesce(region_code,'00')region_code,
       case when dept_name ='大区' and region_name='' then '大区'
            when dept_name ='平台' and region_name='' then '平台'
            else region_name end   region_name,
       coalesce(province_code,'00') province_code,
       coalesce(province_name,'')   province_name,
       coalesce(city_code,'00')  as city_code,
       coalesce(city_name,'')  as city_name,
       coalesce(bd_id,'00')  as bd_id,
       coalesce(bd_name,'')  as bd_name,
       coalesce(classify_large_code,'00') as classify_large_code,
       coalesce(classify_large_name,'') as classify_large_name,
       coalesce(a.classify_middle_code,'00') as classify_middle_code,
       coalesce(classify_middle_name,'') as classify_middle_name,
       b02_entry_num,
       base_entry_num,
       B02_entry_amount,
       B02_no_tax_entry_amount,
       base_entry_amount,
       base_no_tax_entry_amount,
       sdt
FROM
(
SELECT  'week' date_m,
       coalesce(dept_name,'合计')  dept_name,
       coalesce(region_code,'00')   region_code,
       coalesce(region_name,'') region_name,
       coalesce(province_code,'00') province_code,
       coalesce(province_name,'')   province_name,
       coalesce(city_code,'00')  as city_code,
       coalesce(city_name,'')  as city_name,
       coalesce(bd_id,'00')  as bd_id,
       coalesce(bd_name,'')  as bd_name,
       coalesce(classify_large_code,'00') as classify_large_code,
       coalesce(classify_large_name,'') as classify_large_name,
       coalesce(a.classify_middle_code,'00') as classify_middle_code,
       coalesce(classify_middle_name,'') as classify_middle_name,
       b02_entry_num,
       base_entry_num,
       B02_entry_amount,
       B02_no_tax_entry_amount,
       base_entry_amount,
       base_no_tax_entry_amount,
       week_of_year sdt
FROM  csx_analyse_tmp.csx_analyse_tmp_group_purchase_bash_w as a
union all 
SELECT  'months' date_m,
       coalesce(dept_name,'合计')  dept_name,
       coalesce(region_code,'00')   region_code,
       coalesce(region_name,'') region_name,
       coalesce(province_code,'00') province_code,
       coalesce(province_name,'')   province_name,
       coalesce(city_code,'00')  as city_code,
       coalesce(city_name,'')  as city_name,
       coalesce(bd_id,'00')  as bd_id,
       coalesce(bd_name,'')  as bd_name,
       coalesce(classify_large_code,'00') as classify_large_code,
       coalesce(classify_large_name,'') as classify_large_name,
       coalesce(a.classify_middle_code,'00') as classify_middle_code,
       coalesce(classify_middle_name,'') as classify_middle_name,
       b02_entry_num,
       base_entry_num,
       B02_entry_amount,
       B02_no_tax_entry_amount,
       base_entry_amount,
       base_no_tax_entry_amount,
        months sdt 
FROM  csx_analyse_tmp.csx_analyse_tmp_group_purchase_bash_m as a
union all 
SELECT  'quarter' date_m,
       coalesce(dept_name,'合计')  dept_name,
       coalesce(region_code,'00')   region_code,
       coalesce(region_name,'') region_name,
       coalesce(province_code,'00') province_code,
       coalesce(province_name,'')   province_name,
       coalesce(city_code,'00')  as city_code,
       coalesce(city_name,'')  as city_name,
       coalesce(bd_id,'00')  as bd_id,
       coalesce(bd_name,'')  as bd_name,
       coalesce(classify_large_code,'00') as classify_large_code,
       coalesce(classify_large_name,'') as classify_large_name,
       coalesce(a.classify_middle_code,'00') as classify_middle_code,
       coalesce(classify_middle_name,'') as classify_middle_name,
       b02_entry_num,
       base_entry_num,
       B02_entry_amount,
       B02_no_tax_entry_amount,
       base_entry_amount,
       base_no_tax_entry_amount,
       quarter sdt  
FROM  csx_analyse_tmp.csx_analyse_tmp_group_purchase_bash_q as a
union all
SELECT  'year' date_m,
       coalesce(dept_name,'合计')  dept_name,
       coalesce(region_code,'00')   region_code,
       coalesce(region_name,'') region_name,
       coalesce(province_code,'00') province_code,
       coalesce(province_name,'')   province_name,
       coalesce(city_code,'00')  as city_code,
       coalesce(city_name,'')  as city_name,
       coalesce(bd_id,'00')  as bd_id,
       coalesce(bd_name,'')  as bd_name,
       coalesce(classify_large_code,'00') as classify_large_code,
       coalesce(classify_large_name,'') as classify_large_name,
       coalesce(a.classify_middle_code,'00') as classify_middle_code,
       coalesce(classify_middle_name,'') as classify_middle_name,
       b02_entry_num,
       base_entry_num,
       B02_entry_amount,
       B02_no_tax_entry_amount,
       base_entry_amount,
       base_no_tax_entry_amount, 
        year sdt
FROM  csx_analyse_tmp.csx_analyse_tmp_group_purchase_bash_y as a
 )a
;



-- DROP TABLE csx_tmp.temp_purchase_05 ;
-- create   table csx_tmp.temp_purchase_05 as
INSERT OVERWRITE table csx_analyse.csx_analyse_purchase_entry_analysis_di partition(sdt,date_m)
select  id rank_id,
        level_id,
        dept_name,
        region_code,
        region_name,
        province_code,
        province_name,
        city_code,
        city_name,
        bd_id,
        bd_name,
       classify_large_code,
       classify_large_name,
       classify_middle_code,
       classify_middle_name,
       receive_amt,
       no_tax_receive_amt,
       shipped_amt,
       no_tax_shipped_amt,
       net_entry_amount,
       cash_entry_amount,  -- 现金采购
       yh_entry_amount,    -- 云超采购
       all_num,
       cash_entry_num,
       yh_entry_num,
       net_entry_amount_ratio,
       yh_entry_amount_ratio,
       cash_entry_amount_ratio,
       all_num_ratio,
       cash_entry_num_ratio,
       yh_entry_num_ratio,
       no_tax_net_entry_amount,
       cash_no_tax_entry_amount,
       yh_no_tax_entry_amount,
       b02_entry_num,
       base_entry_num,
       B02_entry_amount,
       B02_no_tax_entry_amount,
       base_entry_amount,
       base_no_tax_entry_amount,
       base_entry_amount_ratio,
       base_no_tax_entry_amount_ratio,
       base_entry_num_ratio,
       current_timestamp(),
       sdt,
       date_m,
       substr(sdt,1,4) year
from (
select '1' id,
        date_m,
        level_id,
        dept_name,
        region_code,
        region_name,
        province_code,
        province_name,
        city_code,
        city_name,
        bd_id,
        bd_name,
       '' classify_large_code,
       '' classify_large_name,
       '' classify_middle_code,
       '' classify_middle_name,
       receive_amt,
       no_tax_receive_amt,
       shipped_amt,
       no_tax_shipped_amt,
       net_entry_amount,
       cash_entry_amount,  -- 现金采购
       yh_entry_amount,    -- 云超采购
       all_num,
       cash_entry_num,
       yh_entry_num,
       net_entry_amount_ratio,
       yh_entry_amount_ratio,
       cash_entry_amount_ratio,
       all_num_ratio,
       cash_entry_num_ratio,
       yh_entry_num_ratio,
       no_tax_net_entry_amount,
       cash_no_tax_entry_amount,
       yh_no_tax_entry_amount,
       0 as b02_entry_num,
       0 as base_entry_num,
       0 as B02_entry_amount,
       0 as B02_no_tax_entry_amount,
       0 as base_entry_amount,
       0 as base_no_tax_entry_amount,
       0 as base_entry_amount_ratio,
       0 as base_no_tax_entry_amount_ratio,
       0 as base_entry_num_ratio,
       sdt
from csx_analyse_tmp.csx_analyse_tmp_group_purchase_sum
union all 
select '2' id,
        date_m,
        level_id,
        dept_name,
        region_code,
        region_name,
        province_code,
        province_name,
        city_code,
        city_name,
        bd_id,
        bd_name,
        classify_large_code,
        classify_large_name,
        classify_middle_code,
        classify_middle_name,
       0 as receive_amt,
       0 as no_tax_receive_amt,
       0 as shipped_amt,
       0 as no_tax_shipped_amt,
       0 as net_entry_amount,
       0 as cash_entry_amount,  -- 现金采购
       0 as yh_entry_amount,    -- 云超采购
       0 as all_num,
       0 as cash_entry_num,
       0 as yh_entry_num,
       0 as net_entry_amount_ratio,
       0 as yh_entry_amount_ratio,
       0 as cash_entry_amount_ratio,
       0 as all_num_ratio,
       0 as cash_entry_num_ratio,
       0 as yh_entry_num_ratio,
       0 as no_tax_net_entry_amount,
       0 as cash_no_tax_entry_amount,
       0 as yh_no_tax_entry_amount,
       b02_entry_num,
       base_entry_num,
       B02_entry_amount,
       B02_no_tax_entry_amount,
       base_entry_amount,
       base_no_tax_entry_amount,
       coalesce(base_entry_amount/B02_entry_amount,0) base_entry_amount_ratio,
       coalesce(base_no_tax_entry_amount/B02_no_tax_entry_amount,0) base_no_tax_entry_amount_ratio,
       coalesce(base_entry_num/b02_entry_num,0)       base_entry_num_ratio,       
       sdt
from  csx_analyse_tmp.csx_analyse_tmp_group_purchase_bash_sum 
) a
;



